/* MINI STORIES — part 2: one story for every remaining lesson, each in a different technical field. */
Object.assign(STORY_MORE,{
 pi1:{ field:"Generators & ATS", hero:"Mostafa", icon:"🛢️",
  title:"The call during the blackout", ar:"المكالمة اللي جت وقت انقطاع الكهربا",
  scene:"Mostafa maintains standby generators. A recruiter calls him at the worst possible moment.",
  words:["tied up","call you back","tell me a little about yourself","thrive on new challenges","goal-oriented and ambitious","self-starter","detail-oriented"],
  tech:[["standby generator","مولد احتياطي"],["ATS (automatic transfer switch)","مفتاح التحويل الأوتوماتيكي"],["starting battery","بطارية التشغيل"],["battery terminal","طرف (قطب) البطارية"],["load test","اختبار على حمل"]],
  lines:[
   "Mostafa is a generator technician. He looks after twenty standby generators in shopping malls and office towers in New Cairo.",
   "One evening, the power went off in a big mall. The generator was supposed to start in ten seconds. It didn't.",
   "Mostafa was standing in the dark generator room when his phone rang. It was a recruiter from an energy company.",
   "\"I'm a little tied up just now,\" he said. \"Is it OK if I call you back in an hour?\"",
   "He is very detail-oriented, so he checked everything, step by step. The fuel was full. The ATS was fine.",
   "Then he found it: a loose, dirty terminal on the starting battery. The generator couldn't get enough current to start.",
   "He cleaned and tightened the terminal. The engine started, the ATS transferred the load, and the lights came back on.",
   "An hour later, he called the recruiter back. \"Can you tell me a little about yourself?\" she asked.",
   "\"I thrive on new challenges,\" Mostafa said. \"Tonight, for example, a generator failed to start during a blackout.\"",
   "\"I'm also a self-starter. Nobody asked me, but I created a monthly load test for all twenty generators.\"",
   "\"I'm goal-oriented and ambitious. My goal this year is zero failed starts.\"",
   "The recruiter smiled. \"Tonight wasn't zero,\" she said. \"But it sounds like you're the right person to get there.\""
  ],
  qa:[
   {q:"What does Mostafa look after?", a:"Twenty standby generators in malls and office towers.", opts:["Generators","Elevators"], k:0},
   {q:"What happened in the mall?", a:"The power went off, and the generator didn't start.", opts:["A fire","A blackout"], k:1},
   {q:"How fast was the generator supposed to start?", a:"In ten seconds.", opts:["Ten seconds","Ten minutes"], k:0},
   {q:"Who called him?", a:"A recruiter from an energy company.", opts:["His mother","A recruiter"], k:1},
   {q:"Could he talk right then?", a:"No. He was a little tied up, so he asked to call her back.", opts:["Yes","No, he was tied up"], k:1},
   {q:"Was the fuel tank empty?", a:"No, the fuel was full. And the ATS was fine.", opts:["Empty","Full"], k:1},
   {q:"What was the real problem?", a:"A loose, dirty terminal on the starting battery.", opts:["A battery terminal","No fuel"], k:0},
   {q:"How did he find it?", a:"He's detail-oriented — he checked everything, step by step.", opts:["By luck","Step by step"], k:1},
   {q:"Did he call the recruiter back?", a:"Yes, an hour later.", opts:["Yes","No"], k:0},
   {q:"What does he thrive on?", a:"He thrives on new challenges.", opts:["New challenges","Long holidays"], k:0},
   {q:"Did someone ask him to create the load test?", a:"No! He's a self-starter — nobody asked him.", opts:["Yes, his boss","No, nobody asked"], k:1},
   {q:"What's his goal this year?", a:"Zero failed starts. He's goal-oriented and ambitious.", opts:["Zero failed starts","More overtime"], k:0}
  ],
  pov:"Now be Mostafa on the phone: \"I'm a little tied up just now — is it OK if I call you back?… I thrive on new challenges… I'm a self-starter… I'm detail-oriented… I'm goal-oriented and ambitious.\""
 },

 pi3:{ field:"EV chargers", hero:"Dina", icon:"🚗",
  title:"The charger that must never sleep", ar:"الشاحن اللي لازم يفضل شغال",
  scene:"Dina is an electrical engineer. An electric-car charging company wants to hire her, and now it's time to talk money.",
  words:["fan of your products","somewhere between","open to negotiating based on the entire package","Benefits matter to me as well","give me an idea of the salary range","next steps in the process","most important indicator of success"],
  tech:[["EV (electric vehicle)","عربية كهربا"],["DC fast charger","شاحن سريع DC"],["uptime","نسبة وقت التشغيل"],["connector","الوصلة (الفيشة)"],["remote reset","إعادة تشغيل عن بُعد"]],
  lines:[
   "Dina is an electrical engineer. For three years, she has maintained UPS systems and power panels in office buildings.",
   "Now an electric-car charging company wants to hire her. They are installing DC fast chargers on the roads between Cairo and the coast.",
   "In the interview, she said, \"I've always been a fan of your products. I charged my brother's car at your station in Sokhna.\"",
   "Then the manager asked about salary. Dina asked first: \"Could you give me an idea of the salary range for this role?\"",
   "The manager told her. Dina said, \"I'm looking for somewhere between 35,000 and 42,000 pounds a month.\"",
   "\"But I'm open to negotiating based on the entire package. Benefits matter to me as well — medical insurance, a car and training.\"",
   "Then it was her turn. \"What is the most important indicator of success in this position?\"",
   "\"Uptime,\" said the manager. \"A driver with an empty battery can't wait. Our chargers must work 98% of the time.\"",
   "\"Most faults are simple: a damaged connector, a network problem, or a charger that needs a remote reset.\"",
   "Dina smiled. \"That's like UPS work. The load must never lose power, so you check, you monitor, and you fix before it fails.\"",
   "Finally, she asked, \"What are the next steps in the process?\" — \"A technical test next week,\" said the manager, \"at the Sokhna station.\""
  ],
  qa:[
   {q:"What has Dina maintained for three years?", a:"UPS systems and power panels in office buildings.", opts:["UPS systems","Cars"], k:0},
   {q:"What does the new company install?", a:"DC fast chargers for electric cars.", opts:["EV chargers","Solar panels"], k:0},
   {q:"Is she a fan of their products?", a:"Yes — she charged her brother's car at their station in Sokhna.", opts:["Yes","No"], k:0},
   {q:"Who talked about the salary range first?", a:"Dina asked: \"Could you give me an idea of the salary range?\"", opts:["Dina asked","She never asked"], k:0},
   {q:"What salary is she looking for?", a:"Somewhere between 35,000 and 42,000 pounds a month.", opts:["Exactly 35,000","Between 35,000 and 42,000"], k:1},
   {q:"Is her number fixed?", a:"No. She's open to negotiating based on the entire package.", opts:["Fixed","Open to negotiating"], k:1},
   {q:"Does she care only about salary?", a:"No. Benefits matter to her as well — insurance, a car and training.", opts:["Only salary","Benefits too"], k:1},
   {q:"What's the most important indicator of success?", a:"Uptime — the chargers must work 98% of the time.", opts:["Uptime","Number of emails"], k:0},
   {q:"Why is uptime so important?", a:"Because a driver with an empty battery can't wait.", opts:["Drivers can't wait","It isn't important"], k:0},
   {q:"Are most faults complicated?", a:"No, most are simple: a connector, the network, or a remote reset.", opts:["Very complicated","Mostly simple"], k:1},
   {q:"Why is this job like UPS work?", a:"Because the load must never lose power — you monitor and fix before it fails.", opts:["Power must never stop","It's in an office"], k:0},
   {q:"What's the next step in the process?", a:"A technical test next week at the Sokhna station.", opts:["A technical test","Nothing"], k:0}
  ],
  pov:"Now be Dina: \"I've always been a fan of your products… I'm looking for somewhere between… and… I'm open to negotiating based on the entire package… What are the next steps in the process?\""
 },

 ff2:{ field:"Transformers & telecom sites", hero:"Laila", icon:"🗼",
  title:"Two internships and a village pump", ar:"تدريبين وطلمبة للقرية",
  scene:"Laila is a fresh graduate in electrical power engineering. In her first interview, she talks about her grades, her internships — and a mistake.",
  words:["grades reflect my work","not necessarily a good indication","not an easy feat","managed to succeed","serve my community","voracious reader","two internships under my belt","take ownership of my actions"],
  tech:[["transformer","محوّل كهربا"],["oil test","تحليل زيت المحول"],["telecom tower site","موقع برج اتصالات"],["rectifier","الريكتيفاير (موحّد التيار)"],["solar water pump","طلمبة مياه بالطاقة الشمسية"]],
  lines:[
   "Laila studied electrical power engineering in Assiut. Now she is in her first job interview.",
   "\"Your grades are good, but not excellent,\" said the manager. \"Why?\"",
   "\"I think my grades reflect my work in the subjects I love, like power systems,\" Laila said. \"But grades are not necessarily a good indication of what I can achieve.\"",
   "\"I have two internships under my belt.\" The first was in a transformer workshop. She helped with oil tests and learned how heat and moisture damage a transformer.",
   "The second was on telecom tower sites. She checked rectifiers, batteries and small generators in the desert heat.",
   "In her free time, Laila volunteers. \"It allows me to serve my community,\" she said.",
   "Last summer, her team installed a solar water pump for a village school. They had almost no money and no crane. It was not an easy feat, but they managed to succeed.",
   "\"And I have always been a voracious reader,\" she added. \"I read manuals for fun!\"",
   "Then the manager asked, \"Tell me about a mistake.\"",
   "\"On a tower site, I labelled two battery cables the wrong way round. My supervisor found it before power-up.\"",
   "\"I didn't hide it. I told the team, fixed the labels and made a checklist. I learned how to take ownership of my actions.\"",
   "The manager wrote one word in his notes: honest."
  ],
  qa:[
   {q:"What did Laila study?", a:"Electrical power engineering, in Assiut.", opts:["Power engineering","Medicine"], k:0},
   {q:"Are her grades excellent?", a:"Good, but not excellent.", opts:["Excellent","Good, not excellent"], k:1},
   {q:"Are grades everything?", a:"No. They're not necessarily a good indication of what she can achieve.", opts:["Yes","No"], k:1},
   {q:"How many internships does she have under her belt?", a:"Two internships.", opts:["One","Two"], k:1},
   {q:"What did she do in the transformer workshop?", a:"She helped with oil tests.", opts:["Oil tests","Painting"], k:0},
   {q:"What did she check on the tower sites?", a:"Rectifiers, batteries and small generators.", opts:["Rectifiers and batteries","Mobile phones"], k:0},
   {q:"Why does she volunteer?", a:"It allows her to serve her community.", opts:["To serve her community","For money"], k:0},
   {q:"What did her team install?", a:"A solar water pump for a village school.", opts:["A solar pump","A swimming pool"], k:0},
   {q:"Was it easy?", a:"No, it was not an easy feat — no money, no crane. But they managed to succeed.", opts:["Easy","Not an easy feat"], k:1},
   {q:"What does she read for fun?", a:"Manuals! She's a voracious reader.", opts:["Manuals","Nothing"], k:0},
   {q:"What was her mistake?", a:"She labelled two battery cables the wrong way round.", opts:["Wrong cable labels","She was late"], k:0},
   {q:"Did she hide the mistake?", a:"No. She told the team and made a checklist — she took ownership of her actions.", opts:["She hid it","She took ownership"], k:1},
   {q:"What word did the manager write?", a:"Honest.", opts:["Honest","Lazy"], k:0}
  ],
  pov:"Now be Laila: \"My grades are not necessarily a good indication of what I can achieve… I have two internships under my belt… It was not an easy feat, but I managed to succeed… I learned how to take ownership of my actions.\""
 },

 ff3:{ field:"Electrical panels & safety", hero:"Tamer", icon:"⚡",
  title:"The hot breaker", ar:"البريكر السخن",
  scene:"Tamer is a new maintenance engineer. His thermal camera finds a problem — and his manager asks him to take a dangerous shortcut.",
  words:["bring a lot to the table","play by the rules","follow company guidelines","go-to person","further job progression","fast learner","keen to acquire new skills","critical of myself","OK to say no"],
  tech:[["main switchboard","اللوحة الرئيسية"],["circuit breaker","بريكر (قاطع)"],["thermal camera","كاميرا حرارية"],["hot spot","نقطة سخونة"],["LOTO (lock-out/tag-out)","عزل وقفل وتعليق كارت أمان"],["torque","عزم الربط"]],
  lines:[
   "Tamer joined a factory six months ago as a junior maintenance engineer. As a fresh graduate, he knew he could bring a lot to the table.",
   "He's a fast learner and very keen to acquire new skills, so he took a course in thermal imaging.",
   "One Tuesday, he pointed his thermal camera at the main switchboard. One breaker was 95°C. The others were 40.",
   "It was a hot spot — a loose cable connection. If nobody fixed it, it could start a fire.",
   "His manager said, \"Just tighten it now. Don't stop the production line.\"",
   "But the panel was live. Tamer always plays by the rules and follows company guidelines: never work on a live panel.",
   "\"I'm sorry,\" he said. \"I've learned that it's OK to say no. Let's shut it down safely on Friday, when the line stops.\"",
   "Until Friday, he checked the breaker every two hours with the camera.",
   "On Friday, the team followed LOTO: switch off, lock, tag, test. Then Tamer tightened the cable to the correct torque.",
   "The next scan showed 42°C. Problem solved — and nobody got hurt.",
   "Tamer can be quite critical of himself. \"I should have scanned that panel months ago,\" he said. So he made a monthly thermal-scan schedule for every panel in the factory.",
   "Now he wants to be the go-to person for solving problems — and he'd be interested in further job progression, maybe to reliability engineer."
  ],
  qa:[
   {q:"How long has Tamer worked at the factory?", a:"Six months. He's a fresh graduate.", opts:["Six months","Six years"], k:0},
   {q:"What course did he take?", a:"Thermal imaging — he's keen to acquire new skills.", opts:["Thermal imaging","Cooking"], k:0},
   {q:"How hot was the bad breaker?", a:"95°C. The others were 40.", opts:["45°C","95°C"], k:1},
   {q:"What caused the hot spot?", a:"A loose cable connection.", opts:["A loose connection","The sun"], k:0},
   {q:"What could happen if nobody fixed it?", a:"It could start a fire.", opts:["A fire","Nothing"], k:0},
   {q:"What did his manager want?", a:"To tighten it now, without stopping production.", opts:["Tighten it now","Wait a year"], k:0},
   {q:"Did Tamer work on the live panel?", a:"No. He plays by the rules — never work on a live panel.", opts:["Yes","No"], k:1},
   {q:"What has Tamer learned?", a:"That it's OK to say no.", opts:["It's OK to say no","Always say yes"], k:0},
   {q:"What did he do until Friday?", a:"He checked the breaker every two hours with the camera.", opts:["Nothing","Checked it every two hours"], k:1},
   {q:"What is LOTO?", a:"Switch off, lock, tag and test — before you touch anything.", opts:["A safety procedure","A lottery"], k:0},
   {q:"What was the temperature after the fix?", a:"42°C. Problem solved.", opts:["42°C","95°C"], k:0},
   {q:"Is Tamer easy on himself?", a:"No. He can be quite critical of himself.", opts:["Very easy","Quite critical"], k:1},
   {q:"What does he want to be?", a:"The go-to person for solving problems.", opts:["The go-to person","Invisible"], k:0}
  ],
  pov:"Now be Tamer in an interview: \"As a fresh graduate, I bring a lot to the table… I always play by the rules and follow company guidelines… I've learned that it's OK to say no… I want to be the go-to person for solving problems.\""
 },

 in1:{ field:"Battery monitoring (IoT)", hero:"Rania", icon:"📡",
  title:"The sensor on every battery", ar:"الحسّاس اللي على كل بطارية",
  scene:"Rania manages a new product: a small sensor that watches every battery in a UPS. Now she wants a bigger job in the same company.",
  words:["in charge of managing the creation and release of new products","quite varied","to ensure we stay on schedule","reached a plateau","oversee the day-to-day operations","eager to leverage my expertise","aligns perfectly with my career goals"],
  tech:[["battery monitoring system","نظام مراقبة البطاريات"],["internal resistance","المقاومة الداخلية"],["sensor","حسّاس"],["dashboard","لوحة المتابعة"],["firmware","السوفتوير الداخلي للجهاز"],["field test","تجربة في الموقع"]],
  lines:[
   "Rania works at a company that makes UPS systems. She is in charge of managing the creation and release of new products.",
   "Her latest product is a small battery sensor. You put one on every battery in a UPS, and it measures voltage, temperature and internal resistance.",
   "When a battery starts to get weak, its internal resistance goes up. The sensor sees it months before the battery fails.",
   "Her days are usually quite varied. On Monday, she talks to the engineers about the firmware. On Tuesday, she visits a data centre for a field test.",
   "Every morning, she has a short call with the factory to ensure they stay on schedule.",
   "The launch was a success. Three banks bought the sensors in the first month, and one found forty weak batteries before a power cut.",
   "But after four years, Rania feels she has reached a plateau in her growth.",
   "Now the company wants a new operations manager for the monitoring centre — a room with big screens and a dashboard for every customer's batteries.",
   "In her internal interview, Rania said, \"In this role, I would oversee the day-to-day operations of the monitoring centre.\"",
   "\"I built this product, so I'm eager to leverage my expertise to make the service even better.\"",
   "\"And honestly, this role aligns perfectly with my career goals.\""
  ],
  qa:[
   {q:"What is Rania in charge of?", a:"Managing the creation and release of new products.", opts:["New products","The cafeteria"], k:0},
   {q:"What is her latest product?", a:"A small sensor for every battery in a UPS.", opts:["A battery sensor","A phone app"], k:0},
   {q:"What does the sensor measure?", a:"Voltage, temperature and internal resistance.", opts:["Voltage and temperature","Only the weather"], k:0},
   {q:"What happens to internal resistance when a battery gets weak?", a:"It goes up.", opts:["It goes up","It goes down"], k:0},
   {q:"Are her days all the same?", a:"No, they're usually quite varied.", opts:["All the same","Quite varied"], k:1},
   {q:"Why does she call the factory every morning?", a:"To ensure they stay on schedule.", opts:["To stay on schedule","To chat"], k:0},
   {q:"How many banks bought the sensors in the first month?", a:"Three banks.", opts:["Three","Thirty"], k:0},
   {q:"How many weak batteries did one bank find?", a:"Forty — before a power cut!", opts:["Four","Forty"], k:1},
   {q:"How does Rania feel after four years?", a:"She feels she has reached a plateau in her growth.", opts:["Reached a plateau","Very new"], k:0},
   {q:"What is the new role?", a:"Operations manager for the monitoring centre.", opts:["Operations manager","Driver"], k:0},
   {q:"What would she do in that role?", a:"Oversee the day-to-day operations of the monitoring centre.", opts:["Oversee operations","Sell cars"], k:0},
   {q:"Why is she eager?", a:"She built the product, so she's eager to leverage her expertise.", opts:["To leverage her expertise","To travel"], k:0},
   {q:"Does the role fit her plans?", a:"Yes — it aligns perfectly with her career goals.", opts:["Yes, perfectly","Not at all"], k:0}
  ],
  pov:"Now be Rania: \"I'm in charge of managing the creation and release of new products… My days are usually quite varied… I've reached a plateau in my growth… I'm eager to leverage my expertise… It aligns perfectly with my career goals.\""
 },

 ex1:{ field:"Data-centre build", hero:"Sherif", icon:"🏗️",
  title:"Forty days to power on", ar:"٤٠ يوم علشان الداتا سنتر يشتغل",
  scene:"Sherif builds data centres. In a senior interview, he tells the story of his hardest project.",
  words:["heard great things about your work","worked my way up","significant impact on the company's bottom line","complex project with many moving parts","diverse background","led my team","reiterate my enthusiasm"],
  tech:[["Tier III","مستوى اعتمادية للداتا سنتر"],["commissioning","الاستلام والتشغيل التجريبي"],["fire suppression","نظام إطفاء الحريق"],["load bank","حمل صناعي للاختبار"],["handover","التسليم"]],
  lines:[
   "Sherif is interviewing for director of engineering at a large telecom company.",
   "The CEO began, \"I've heard great things about your work on the Smart Village data centre.\"",
   "\"Thank you,\" said Sherif. \"I started as a site electrician twenty years ago, and I worked my way up to my current role.\"",
   "\"I have a diverse background in the industry: power, cooling, networks — and a few years in sales.\"",
   "Then he told the story. The data centre was a Tier III project, and the client wanted it running in forty days.",
   "It was a complex project with many moving parts: two generators, four UPS modules, six chillers, fire suppression and three hundred racks.",
   "Every supplier had a different schedule. The generators arrived late, and the chillers arrived early with no place to put them.",
   "Sherif held a stand-up meeting every morning at seven. Every problem had an owner and a deadline.",
   "For commissioning, his team tested everything with load banks: they cut the utility power again and again and watched the UPS and generators take over.",
   "The handover was on day thirty-nine. The client signed two more sites, and it had a significant impact on the company's bottom line.",
   "\"In the same year, I led my team to exceed sales targets by thirty percent.\"",
   "At the end, Sherif said, \"I'd like to reiterate my enthusiasm for the role. I'd love to build your next ten sites.\""
  ],
  qa:[
   {q:"What role is Sherif interviewing for?", a:"Director of engineering at a telecom company.", opts:["Director","Intern"], k:0},
   {q:"What has the CEO heard?", a:"Great things about his work on the Smart Village data centre.", opts:["Great things","Bad news"], k:0},
   {q:"How did Sherif start?", a:"As a site electrician. He worked his way up.", opts:["As a site electrician","As a CEO"], k:0},
   {q:"Is his background narrow?", a:"No, it's diverse: power, cooling, networks and sales.", opts:["Narrow","Diverse"], k:1},
   {q:"How many days did the client give him?", a:"Forty days.", opts:["Forty","Four hundred"], k:0},
   {q:"Was it a simple project?", a:"No. It was a complex project with many moving parts.", opts:["Simple","Complex"], k:1},
   {q:"Which equipment arrived late?", a:"The generators.", opts:["The generators","The chillers"], k:0},
   {q:"When was the daily meeting?", a:"Every morning at seven.", opts:["At seven","At midnight"], k:0},
   {q:"What did they test with during commissioning?", a:"Load banks — they cut the power again and again.", opts:["Load banks","Nothing"], k:0},
   {q:"When was the handover?", a:"On day thirty-nine — one day early.", opts:["Day 39","Day 60"], k:0},
   {q:"What was the impact on the company?", a:"A significant impact on the bottom line — two more sites.", opts:["Significant","None"], k:0},
   {q:"What did he want to reiterate?", a:"His enthusiasm for the role.", opts:["His enthusiasm","His complaints"], k:0}
  ],
  pov:"Now be Sherif: \"I worked my way up to my current role… It was a complex project with many moving parts… It had a significant impact on the company's bottom line… I'd like to reiterate my enthusiasm for the role.\""
 },

 em1:{ field:"CCTV & security systems", hero:"Mahmoud", icon:"📹",
  title:"The camera that forgot everything", ar:"الكاميرا اللي نسيت كل حاجة",
  scene:"Mahmoud looks after the CCTV system at a hotel. Three days of video are missing, and he needs help from a stranger — by email.",
  words:["subject line","I hope this email finds you well","I was referred to you by","The purpose of this email is to address","reaching out to you today to ask a quick question","look forward to hearing back from you soon"],
  tech:[["CCTV","كاميرات المراقبة"],["NVR (network video recorder)","جهاز تسجيل الكاميرات"],["hard disk / RAID","الهارد ديسك / مصفوفة الهاردات"],["footage","التسجيلات"],["firmware update","تحديث السوفتوير الداخلي"]],
  lines:[
   "Mahmoud is the security-systems technician at a big hotel in Hurghada. He looks after 180 cameras and four NVRs.",
   "One morning, the manager asked for video from the car park. A guest's car had been damaged.",
   "Mahmoud opened the NVR. There was no footage for the last three days.",
   "He checked the hard disks. One disk in the RAID had failed, and after a firmware update, the NVR had stopped recording.",
   "He needed an expert. A friend at another hotel gave him the name of the supplier's senior engineer, Mr. Adel.",
   "Mahmoud wrote the email carefully. First, he made sure the subject line was clear: \"NVR stopped recording after firmware update — urgent\".",
   "\"Dear Mr. Adel, I hope this email finds you well. I was referred to you by Hassan Fathy at the Sunrise Hotel.\"",
   "\"The purpose of this email is to address a recording failure on two of our NVRs.\"",
   "\"I'm also reaching out to you today to ask a quick question: can the missing footage be recovered from the failed disk?\"",
   "\"I have attached the logs and photos. I look forward to hearing back from you soon.\"",
   "Mr. Adel replied in one hour. The footage was lost, but he sent a fix for the firmware — and Mahmoud added an alarm that tells him when any camera stops recording."
  ],
  qa:[
   {q:"Where does Mahmoud work?", a:"At a big hotel in Hurghada.", opts:["A hotel","A hospital"], k:0},
   {q:"How many cameras does he look after?", a:"180 cameras and four NVRs.", opts:["18","180"], k:1},
   {q:"What video did the manager want?", a:"Video from the car park — a guest's car was damaged.", opts:["The car park","The pool"], k:0},
   {q:"How much footage was missing?", a:"The last three days.", opts:["Three hours","Three days"], k:1},
   {q:"What had failed?", a:"One disk in the RAID — and the NVR stopped recording after a firmware update.", opts:["A disk","The camera lens"], k:0},
   {q:"Who referred him to Mr. Adel?", a:"His friend Hassan Fathy at another hotel.", opts:["A friend","His mother"], k:0},
   {q:"Was his subject line vague?", a:"No, it was clear: \"NVR stopped recording after firmware update — urgent\".", opts:["Vague","Clear"], k:1},
   {q:"How did he start the email?", a:"\"Dear Mr. Adel, I hope this email finds you well.\"", opts:["\"Hey man\"","\"Dear Mr. Adel\""], k:1},
   {q:"What was the purpose of the email?", a:"To address a recording failure on two NVRs.", opts:["A recording failure","A party"], k:0},
   {q:"What quick question did he ask?", a:"Can the missing footage be recovered?", opts:["Can it be recovered?","What's the weather?"], k:0},
   {q:"How did he end the email?", a:"\"I look forward to hearing back from you soon.\"", opts:["\"Bye\"","\"I look forward to hearing back\""], k:1},
   {q:"How fast did Mr. Adel reply?", a:"In one hour.", opts:["One hour","One month"], k:0},
   {q:"What did Mahmoud add?", a:"An alarm that tells him when any camera stops recording.", opts:["An alarm","More cameras"], k:0}
  ],
  pov:"Now write Mahmoud's email out loud: \"Dear Mr. Adel, I hope this email finds you well. I was referred to you by… The purpose of this email is to address… I'm reaching out to you today to ask a quick question… I look forward to hearing back from you soon.\""
 },

 em3:{ field:"Cybersecurity & backups", hero:"Heba", icon:"🛡️",
  title:"The email that asked for passwords", ar:"الإيميل اللي طلب الباسوردات",
  scene:"Heba is the IT security officer at a pharmaceutical company. A fake email is spreading, and she must warn everyone — fast and clearly.",
  words:["It's important to note that","As a result","EOD","Please don't hesitate to reach out","confirm that you've received","Best regards","Sincerely"],
  tech:[["phishing","إيميل احتيال"],["ransomware","فيروس الفدية"],["backup","النسخة الاحتياطية"],["patch","تحديث أمني"],["MFA (multi-factor authentication)","التحقق بخطوتين"]],
  lines:[
   "Heba is the IT security officer at a pharmaceutical company in 6th of October City.",
   "On Sunday morning, twelve employees received a fake email. It looked like it came from IT: \"Your password expires today. Click here.\"",
   "It was phishing. Two people clicked the link and typed their passwords.",
   "Heba acted fast. She reset both passwords and checked the servers for ransomware. Nothing was encrypted — the backups were safe.",
   "Then she wrote to all staff: \"It's important to note that IT will never ask for your password by email.\"",
   "\"As a result of this attack, we will turn on multi-factor authentication for every account.\"",
   "\"All laptops must install the new security patch by EOD today.\"",
   "\"Please don't hesitate to reach out if you have any questions.\" And she ended with \"Best regards, Heba\".",
   "Next, she wrote a formal letter to the company's bank, because one of the two users worked in finance.",
   "\"Could you please confirm that you've received this message?\" she wrote. This time, she ended with \"Sincerely\".",
   "The bank confirmed in twenty minutes. No money moved, and on Monday, every employee had a two-minute training on how to spot phishing."
  ],
  qa:[
   {q:"What is Heba's job?", a:"IT security officer at a pharmaceutical company.", opts:["IT security officer","Accountant"], k:0},
   {q:"What did the fake email say?", a:"\"Your password expires today. Click here.\"", opts:["Password expires","You won a prize"], k:0},
   {q:"What kind of attack was it?", a:"Phishing.", opts:["Phishing","A power cut"], k:0},
   {q:"How many people typed their passwords?", a:"Two people.", opts:["Two","Twelve"], k:0},
   {q:"Were the backups safe?", a:"Yes, nothing was encrypted — the backups were safe.", opts:["Yes","No"], k:0},
   {q:"Will IT ever ask for your password by email?", a:"Never. It's important to note that.", opts:["Sometimes","Never"], k:1},
   {q:"What will happen as a result of the attack?", a:"Multi-factor authentication for every account.", opts:["MFA for everyone","Nothing"], k:0},
   {q:"When must the patch be installed?", a:"By EOD — by the end of the day today.", opts:["By EOD today","Next month"], k:0},
   {q:"How did she close the email to staff?", a:"\"Best regards\" — friendly but professional.", opts:["\"Best regards\"","\"Love\""], k:0},
   {q:"Why did she write to the bank?", a:"Because one of the two users worked in finance.", opts:["A finance user clicked","To open an account"], k:0},
   {q:"What did she ask the bank?", a:"\"Could you please confirm that you've received this message?\"", opts:["To confirm receipt","For a loan"], k:0},
   {q:"How did she close the formal letter?", a:"\"Sincerely\" — more formal.", opts:["\"Sincerely\"","\"Cheers\""], k:0},
   {q:"Did any money move?", a:"No. And on Monday everyone had phishing training.", opts:["Yes","No"], k:1}
  ],
  pov:"Now be Heba writing to staff: \"It's important to note that… As a result,… by EOD today… Please don't hesitate to reach out if you have any questions. Best regards.\""
 },

 em4:{ field:"Battery storage (BESS)", hero:"Ziad", icon:"🌾",
  title:"Sun by day, batteries by night", ar:"الشمس بالنهار والبطاريات بالليل",
  scene:"Ziad sells solar systems to farms. Farmers want power at night too — so he needs a battery partner.",
  words:["take a moment to introduce myself","potential synergies between our organizations","kindly provide the following information","appreciate your prompt attention","follow up on our meeting","keep the momentum going","As per our recent discussion"],
  tech:[["BESS (battery energy storage system)","نظام تخزين طاقة بالبطاريات"],["kWh","كيلووات ساعة (سعة التخزين)"],["hybrid inverter","إنفرتر هايبرد"],["cycle life","عدد دورات الشحن"],["diesel savings","توفير السولار"]],
  lines:[
   "Ziad sells solar systems to farms in Minya. The farmers love free power in the day, but at night their pumps still run on diesel.",
   "Ziad found a company that makes battery energy storage systems — big lithium batteries in a container.",
   "He wrote to their sales director: \"I wanted to take a moment to introduce myself. I'm Ziad, and my company has installed solar on sixty farms.\"",
   "\"I believe there may be potential synergies between our organizations: we have the farms, and you have the batteries.\"",
   "They met in Cairo. The director liked the idea, and they agreed on a pilot farm.",
   "The next day, Ziad wrote again: \"I wanted to follow up on our meeting. As per our recent discussion, we will start with one farm: 200 kWh of storage and a hybrid inverter.\"",
   "\"To keep the momentum going, I'd like to propose the following next steps: a site visit next week, then a price offer.\"",
   "\"Could you kindly provide the following information? The cycle life of the batteries, the warranty, and the delivery time.\"",
   "\"We appreciate your prompt attention to this matter.\"",
   "Three months later, the pilot farm ran its pumps all night on solar energy stored in the batteries.",
   "The farmer saved 60% on diesel — and his neighbours started calling Ziad."
  ],
  qa:[
   {q:"Where are Ziad's customers?", a:"On farms in Minya.", opts:["In Minya","In Dubai"], k:0},
   {q:"What runs the pumps at night?", a:"Diesel — the sun is gone.", opts:["Diesel","The moon"], k:0},
   {q:"What does the other company make?", a:"Battery energy storage systems.", opts:["Batteries","Tractors"], k:0},
   {q:"How did Ziad start his first email?", a:"\"I wanted to take a moment to introduce myself.\"", opts:["\"Introduce myself\"","\"Pay me now\""], k:0},
   {q:"What synergies did he see?", a:"He has the farms, and they have the batteries.", opts:["Farms + batteries","Nothing"], k:0},
   {q:"What did they agree in Cairo?", a:"A pilot farm.", opts:["A pilot farm","A holiday"], k:0},
   {q:"How much storage for the pilot?", a:"200 kWh, with a hybrid inverter.", opts:["20 kWh","200 kWh"], k:1},
   {q:"How did he write about the meeting?", a:"\"I wanted to follow up on our meeting. As per our recent discussion…\"", opts:["\"As per our recent discussion\"","\"Forget the meeting\""], k:0},
   {q:"Why did he propose next steps?", a:"To keep the momentum going.", opts:["To keep the momentum going","To stop the project"], k:0},
   {q:"What information did he ask for?", a:"Cycle life, warranty and delivery time.", opts:["Cycle life and warranty","Their home address"], k:0},
   {q:"What did he appreciate?", a:"Their prompt attention to this matter.", opts:["Prompt attention","A slow reply"], k:0},
   {q:"How much diesel did the farmer save?", a:"He saved 60% on diesel.", opts:["6%","60%"], k:1}
  ],
  pov:"Now be Ziad writing: \"I wanted to take a moment to introduce myself… There may be potential synergies between our organizations… I wanted to follow up on our meeting… To keep the momentum going, I'd like to propose the following next steps.\""
 },

 em5:{ field:"Maintenance contracts", hero:"Salma", icon:"🧰",
  title:"The shutdown nobody wanted", ar:"الفصل اللي محدش كان عايزه",
  scene:"Salma coordinates maintenance for a UPS service company. She has to book a shutdown, announce good news — and chase an unpaid invoice.",
  words:["proposed dates and times","which option works best for you","We're excited to announce","Your input is invaluable","gentle reminder","remains unpaid","kindly arrange for the payment","Thank you for your business"],
  tech:[["AMC (annual maintenance contract)","عقد صيانة سنوي"],["preventive maintenance (PM)","صيانة وقائية"],["battery replacement","تغيير البطاريات"],["maintenance bypass","التحويل على الباي باس للصيانة"],["24/7 hotline","خط طوارئ ٢٤ ساعة"]],
  lines:[
   "Salma is the service coordinator at a company that maintains UPS systems. She manages sixty annual maintenance contracts.",
   "A bank's UPS needs new batteries. To replace them safely, the UPS must go to maintenance bypass for four hours.",
   "Nobody likes a shutdown, so Salma wrote carefully: \"Here are my proposed dates and times: Friday the 10th from 6 a.m., or Saturday the 11th from 10 p.m.\"",
   "\"Please let me know which option works best for you.\" The bank chose Friday morning.",
   "The battery replacement went perfectly. The team finished in three hours.",
   "The next week, Salma sent an email to all customers: \"We're excited to announce our new 24/7 hotline for UPS emergencies.\"",
   "She also added a short survey: \"Your input is invaluable. Tell us how we can serve you better.\"",
   "But one customer, a plastics factory, had not paid for its preventive maintenance visit two months ago.",
   "Salma didn't get angry. She wrote: \"This is a gentle reminder that your invoice remains unpaid.\"",
   "\"Please kindly arrange for the payment by the end of the month.\"",
   "She ended with \"Thank you for your business.\" The payment arrived four days later."
  ],
  qa:[
   {q:"What does Salma's company maintain?", a:"UPS systems — sixty annual contracts.", opts:["UPS systems","Cars"], k:0},
   {q:"What does the bank's UPS need?", a:"New batteries.", opts:["New batteries","A new paint"], k:0},
   {q:"How long must the UPS be on bypass?", a:"Four hours.", opts:["Four hours","Four days"], k:0},
   {q:"Did Salma choose the date herself?", a:"No, she sent proposed dates and times.", opts:["She chose","She proposed options"], k:1},
   {q:"What did she ask the bank?", a:"Which option works best for them.", opts:["Which option works best","Why they're late"], k:0},
   {q:"Which option did the bank choose?", a:"Friday morning.", opts:["Friday morning","Saturday night"], k:0},
   {q:"How long did the job take?", a:"Three hours — one hour early.", opts:["Three hours","Eight hours"], k:0},
   {q:"What were they excited to announce?", a:"A new 24/7 hotline for UPS emergencies.", opts:["A 24/7 hotline","Higher prices"], k:0},
   {q:"Why did she add a survey?", a:"Because customers' input is invaluable.", opts:["Input is invaluable","To waste time"], k:0},
   {q:"Who didn't pay?", a:"A plastics factory.", opts:["The bank","A plastics factory"], k:1},
   {q:"Was her reminder angry?", a:"No, it was a gentle reminder.", opts:["Angry","Gentle"], k:1},
   {q:"How did she end the email?", a:"\"Thank you for your business.\"", opts:["\"Thank you for your business\"","\"Pay or else\""], k:0},
   {q:"When did the payment arrive?", a:"Four days later.", opts:["Four days later","Never"], k:0}
  ],
  pov:"Now be Salma: \"Here are my proposed dates and times… Please let me know which option works best for you… We're excited to announce… This is a gentle reminder that your invoice remains unpaid… Thank you for your business.\""
 },

 em6:{ field:"Energy exhibitions & careers", hero:"Adel", icon:"🎟️",
  title:"The hybrid inverter at booth 12", ar:"الإنفرتر الهايبرد في جناح ١٢",
  scene:"Adel is an energy engineer looking for his next job. An exhibition, a demo and a few good emails change everything.",
  words:["excited to invite you to our upcoming event","friendly reminder that the deadline is fast approaching","express my interest in the position","great fit for the role","Thank you for considering my application","acknowledge receipt of your message","available for a 15–20 minute call"],
  tech:[["exhibition booth","جناح في المعرض"],["hybrid inverter","إنفرتر هايبرد (شمس + بطاريات + شبكة)"],["demo","عرض عملي"],["grid","الشبكة القومية"],["off-grid","منفصل عن الشبكة"]],
  lines:[
   "Adel has worked for eight years with UPS systems and solar inverters. He wants to join a company that designs its own products.",
   "One day, he got an email: \"We're excited to invite you to our upcoming event: the Egypt Energy exhibition, booth 12.\"",
   "At booth 12, a company was showing a new hybrid inverter. It could run from solar, batteries or the grid — and switch between them in milliseconds.",
   "Adel asked so many good questions that the product manager gave him her card.",
   "A week later, she wrote again: \"This is just a friendly reminder that the deadline for our field engineer position is fast approaching.\"",
   "Adel sent his CV the same evening: \"I am writing to express my interest in the position of senior field engineer.\"",
   "\"With eight years of UPS and inverter experience, I believe I would be a great fit for the role.\"",
   "\"Thank you for considering my application.\"",
   "The HR manager replied: \"I wanted to acknowledge receipt of your message. The team will review it this week.\"",
   "Two days later: \"Would you be available for a 15–20 minute call on Thursday?\"",
   "On the call, they asked him to explain how a hybrid inverter works off-grid. Adel explained it clearly — and in simple English.",
   "He got the job."
  ],
  qa:[
   {q:"How long has Adel worked with UPS and inverters?", a:"Eight years.", opts:["Eight years","Eight months"], k:0},
   {q:"What was he invited to?", a:"The Egypt Energy exhibition, booth 12.", opts:["An exhibition","A wedding"], k:0},
   {q:"What was shown at booth 12?", a:"A new hybrid inverter.", opts:["A hybrid inverter","A new car"], k:0},
   {q:"What can the inverter run from?", a:"Solar, batteries or the grid.", opts:["Solar, batteries or grid","Only diesel"], k:0},
   {q:"Why did the product manager give him her card?", a:"Because he asked so many good questions.", opts:["Good questions","He was lost"], k:0},
   {q:"What was the friendly reminder about?", a:"The deadline for the position was fast approaching.", opts:["The deadline","A party"], k:0},
   {q:"When did he send his CV?", a:"The same evening.", opts:["The same evening","Next year"], k:0},
   {q:"How did his email begin?", a:"\"I am writing to express my interest in the position.\"", opts:["\"Express my interest\"","\"Give me a job\""], k:0},
   {q:"Why is he a great fit?", a:"Eight years of UPS and inverter experience.", opts:["His experience","His car"], k:0},
   {q:"What did HR do first?", a:"Acknowledged receipt of his message.", opts:["Acknowledged receipt","Ignored him"], k:0},
   {q:"How long was the call?", a:"15 to 20 minutes.", opts:["15–20 minutes","Two hours"], k:0},
   {q:"What did he explain on the call?", a:"How a hybrid inverter works off-grid.", opts:["A hybrid inverter","Football"], k:0},
   {q:"Did he get the job?", a:"Yes, he did!", opts:["Yes","No"], k:0}
  ],
  pov:"Now be Adel writing: \"I am writing to express my interest in the position… I believe I would be a great fit for the role… Thank you for considering my application.\" Then be HR: \"I wanted to acknowledge receipt of your message… Would you be available for a 15–20 minute call?\""
 }
});
