/* MORE MINI STORIES — set in the learner's own field (IT, servers, solar, control cards, VFDs).
   Each story is attached to a book lesson and reuses that lesson's phrases. */
const STORY_MORE={
 em2:{ field:"IT department", fieldAr:"قسم الـ IT", hero:"Omar", icon:"🖧",
  title:"The Monday morning outage", ar:"العطل اللي وقّف الشركة يوم الاتنين",
  scene:"Omar is the IT support lead at a factory. Today he has to fix the network — and then write the right emails.",
  words:["Please find attached","As you may recall","misunderstanding","committed to making things right","on track","at your earliest convenience","bringing this matter to our attention"],
  tech:[["core switch","السويتش الرئيسي للشبكة"],["power supply (PSU)","الباور سبلاي"],["helpdesk ticket","بلاغ دعم فني"],["outage","انقطاع الخدمة"],["redundant","احتياطي مزدوج"],["purchase order (PO)","أمر شراء"]],
  lines:[
   "Omar is the IT support lead at a factory in 10th of Ramadan City. He looks after 300 laptops, 40 printers and the whole network.",
   "One Monday at 8:05, nobody could open the ERP system. The helpdesk received sixty tickets in ten minutes.",
   "Omar ran to the server room. The core switch was dead — its power supply had failed over the weekend.",
   "As you may recall, Omar had asked for a spare switch last year. The request was never approved.",
   "He moved the key servers to a backup switch, and by 9:30 the ERP was back online.",
   "Then he emailed the managers: \"Please find attached the incident report for your review.\"",
   "The finance manager replied angrily: \"Why did IT shut down our system on a busy Monday?\"",
   "Omar stayed polite: \"There seems to have been a misunderstanding. The outage was caused by a hardware fault, not a planned shutdown.\"",
   "He added: \"I apologize for the disruption, and I am committed to making things right. We will install a redundant switch with two power supplies.\"",
   "\"We're on track to finish the upgrade by Thursday. Please approve the purchase order at your earliest convenience.\"",
   "The next morning, the CEO wrote back: \"Thank you for bringing this matter to our attention. Approved.\""
  ],
  qa:[
   {q:"Is Omar a sales manager?", a:"No, he isn't. He's the IT support lead at a factory.", opts:["Yes","No"], k:1},
   {q:"How many laptops does he look after?", a:"Three hundred laptops — and forty printers and the whole network.", opts:["30","300"], k:1},
   {q:"What happened at 8:05 on Monday?", a:"Nobody could open the ERP system.", opts:["The ERP stopped","The printers ran out of paper"], k:0},
   {q:"How many tickets did the helpdesk get?", a:"Sixty tickets in ten minutes!", opts:["Six","Sixty"], k:1},
   {q:"What was dead?", a:"The core switch. Its power supply had failed over the weekend.", opts:["The core switch","A laptop"], k:0},
   {q:"Did Omar ask for a spare switch before?", a:"Yes. As you may recall, he asked last year, but it was never approved.", opts:["Yes, last year","No, never"], k:0},
   {q:"When was the ERP back online?", a:"By 9:30 — he moved the key servers to a backup switch.", opts:["By 9:30","Next week"], k:0},
   {q:"What did he attach to his email?", a:"The incident report. \"Please find attached the incident report for your review.\"", opts:["The incident report","A photo of his cat"], k:0},
   {q:"Did IT shut down the system on purpose?", a:"No! There seems to have been a misunderstanding — it was a hardware fault.", opts:["Yes, on purpose","No, it was a hardware fault"], k:1},
   {q:"How does Omar promise to make things right?", a:"He's committed to making things right with a redundant switch with two power supplies.", opts:["A redundant switch","Longer holidays"], k:0},
   {q:"Is the upgrade late?", a:"No. They're on track to finish by Thursday.", opts:["It's late","It's on track"], k:1},
   {q:"When should the manager approve the PO?", a:"At his earliest convenience — as soon as he can.", opts:["At his earliest convenience","Next year"], k:0},
   {q:"What did the CEO say?", a:"\"Thank you for bringing this matter to our attention. Approved.\"", opts:["\"Approved\"","\"No budget\""], k:0}
  ],
  pov:"Now be Omar and write the email out loud: \"Dear all, please find attached… There seems to have been a misunderstanding… I am committed to making things right… We're on track to…\""
 },

 ex2:{ field:"Servers & data centre", fieldAr:"السيرفرات والداتا سنتر", hero:"Nour", icon:"🗄️",
  title:"The servers that died at 3 p.m.", ar:"السيرفرات اللي كانت بتقفل الساعة ٣",
  scene:"Nour is a data-centre engineer at a bank. Two servers keep shutting down, and everyone is blaming someone else.",
  words:["natural leader","clearly, both verbally and in writing","root cause","calm and composed","defensive or personal","win-win solution","back on track"],
  tech:[["rack","الراك (دولاب السيرفرات)"],["thermal shutdown","فصل بسبب الحرارة"],["blanking panel","غطاء للفتحات الفاضية في الراك"],["cold-aisle containment","عزل الممر البارد"],["under warranty","تحت الضمان"],["batch job","مهمة تشغيل مجمّعة"]],
  lines:[
   "Nour is a data-centre engineer at a bank in Cairo. Her team runs 120 servers in two rooms.",
   "In July, two database servers in rack 7 started shutting down every afternoon at about 3 p.m.",
   "The software team said, \"It's the hardware.\" The hardware vendor said, \"It's your software.\" Everyone was angry.",
   "Nour stayed calm and composed. She avoided getting defensive or personal and said, \"Let's find the root cause first.\"",
   "She checked the server logs. Every shutdown had the same message: thermal shutdown — CPU over temperature.",
   "So it wasn't the software. The servers were overheating.",
   "She measured the air in front of the rack: 38°C. It should be below 27.",
   "The root cause was simple. The empty spaces in the rack had no blanking panels, so hot air from the back came round to the front. And one server fan had failed.",
   "Nour explained it clearly, both verbally in the meeting and in writing, in a short report with photos.",
   "Then she proposed a win-win solution: the vendor replaced the fan under warranty, facilities installed blanking panels and cold-aisle containment, and the software team moved its heavy batch job to 2 a.m.",
   "In one week, the project was back on track. There were no shutdowns for ninety days — and her manager called her a natural leader."
  ],
  qa:[
   {q:"Where does Nour work?", a:"In the data centre of a bank in Cairo.", opts:["At a bank","At a hotel"], k:0},
   {q:"When did the servers shut down?", a:"Every afternoon at about 3 p.m.", opts:["At 3 a.m.","At about 3 p.m."], k:1},
   {q:"Did the teams agree?", a:"No. The software team blamed the hardware, and the vendor blamed the software.", opts:["Yes","No, they blamed each other"], k:1},
   {q:"Did Nour get angry too?", a:"No. She stayed calm and composed.", opts:["Yes, very","No, she stayed calm"], k:1},
   {q:"Did she get personal?", a:"No, she avoided getting defensive or personal.", opts:["Yes","No"], k:1},
   {q:"What did she want to find first?", a:"The root cause.", opts:["The root cause","Someone to blame"], k:0},
   {q:"What did the logs say?", a:"Thermal shutdown — CPU over temperature.", opts:["Thermal shutdown","Password expired"], k:0},
   {q:"Was it a software problem?", a:"No. The servers were overheating.", opts:["Yes, software","No, overheating"], k:1},
   {q:"How hot was the air in front of the rack?", a:"38°C — it should be below 27.", opts:["18°C","38°C"], k:1},
   {q:"Why was hot air coming to the front?", a:"Because there were no blanking panels in the empty spaces.", opts:["No blanking panels","Too many windows"], k:0},
   {q:"How did she explain it?", a:"Clearly, both verbally in the meeting and in writing, with photos.", opts:["Only by phone","Verbally and in writing"], k:1},
   {q:"Who paid for the new fan?", a:"Nobody — the vendor replaced it under warranty. A win-win solution.", opts:["The bank","The vendor, under warranty"], k:1},
   {q:"When does the batch job run now?", a:"At 2 a.m., when the servers are cooler and less busy.", opts:["At 3 p.m.","At 2 a.m."], k:1},
   {q:"What did her manager call her?", a:"A natural leader — the project was back on track in one week.", opts:["A natural leader","A trouble-maker"], k:0}
  ],
  pov:"Now be Nour in a job interview: \"I try to stay calm and composed… I try to understand the root cause of the problem… I always strive for a win-win solution… We were able to get the project back on track.\""
 },

 ex3:{ field:"Solar power plants", fieldAr:"محطات الطاقة الشمسية", hero:"Youssef", icon:"☀️",
  title:"The solar plant that lost 18%", ar:"المحطة الشمسية اللي إنتاجها وقع ١٨٪",
  scene:"Youssef runs operations and maintenance at a big solar plant in Aswan. Production is falling, and the owners want answers.",
  words:["stays current","industry news and publications","keeps an eye on","data-driven approach","daily check-in meeting","urgency and importance","20% of tasks","greatest impact"],
  tech:[["O&M","التشغيل والصيانة"],["inverter","الانفرتر"],["string","سلسلة ألواح متوصلة مع بعض"],["insulation fault","عطل عزل (تسريب للأرضي)"],["junction box","علبة التوصيل"],["SCADA / monitoring","نظام المراقبة"]],
  lines:[
   "Youssef is the O&M manager at a 50 MW solar plant in Benban, near Aswan. His team keeps 150,000 panels and 20 inverters running.",
   "In April, the plant produced 18% less energy than planned. The owners wanted answers — fast.",
   "Youssef didn't guess. He took a data-driven approach and compared every inverter and every string in the monitoring system.",
   "The data showed three problems. First, a sandstorm had covered the panels with dust.",
   "Second, twelve strings were producing zero current. Their fuses had blown.",
   "Third, inverter 14 kept tripping with an insulation fault. Water had got into a DC junction box, and a cable was damaged.",
   "There were too many jobs, so he analyzed the urgency and importance of each task.",
   "He focused on the 20% of tasks that had the greatest impact. Inverter 14 came first, because one inverter is 5% of the whole plant.",
   "He also implemented a daily check-in meeting: fifteen minutes at 7 a.m., before the sun gets too hot.",
   "Youssef stays current by reading industry news and publications, so he knew about robots that clean panels without water. He proposed a pilot.",
   "He keeps an eye on the market, too. Panel prices were falling, so replacing the damaged modules was cheap.",
   "By the end of May, the plant was back to 99% of its target."
  ],
  qa:[
   {q:"Where is Youssef's plant?", a:"In Benban, near Aswan.", opts:["Near Aswan","Near Alexandria"], k:0},
   {q:"How big is it?", a:"50 MW — 150,000 panels and 20 inverters.", opts:["5 MW","50 MW"], k:1},
   {q:"How much less energy did it produce in April?", a:"18% less than planned.", opts:["8%","18%"], k:1},
   {q:"Did Youssef guess the problem?", a:"No. He took a data-driven approach.", opts:["Yes, he guessed","No, he used the data"], k:1},
   {q:"What covered the panels?", a:"Dust from a sandstorm.", opts:["Snow","Dust"], k:1},
   {q:"Why were twelve strings producing zero current?", a:"Because their fuses had blown.", opts:["Blown fuses","It was night"], k:0},
   {q:"What fault did inverter 14 show?", a:"An insulation fault — water had got into a DC junction box.", opts:["Insulation fault","Low battery"], k:0},
   {q:"Did he do every job at the same time?", a:"No. He analyzed the urgency and importance of each task.", opts:["Yes","No"], k:1},
   {q:"Why did inverter 14 come first?", a:"Because it had the greatest impact — one inverter is 5% of the plant.", opts:["It was the greatest impact","It was the closest"], k:0},
   {q:"When is the daily check-in meeting?", a:"At 7 a.m., for fifteen minutes, before the sun gets too hot.", opts:["7 a.m.","7 p.m."], k:0},
   {q:"How does he stay current?", a:"By reading industry news and publications.", opts:["Industry news","He doesn't"], k:0},
   {q:"What do the new robots clean with?", a:"No water at all — they clean panels dry.", opts:["Lots of water","No water"], k:1},
   {q:"Why was replacing the modules cheap?", a:"He keeps an eye on the market — panel prices were falling.", opts:["Prices were falling","A friend gave them free"], k:0},
   {q:"Where was the plant by the end of May?", a:"Back to 99% of its target.", opts:["Still at 82%","Back to 99%"], k:1}
  ],
  pov:"Now be Youssef answering \"How do you prioritize?\": \"I took a data-driven approach… I analyze the urgency and importance of each task… I focus on the 20% of tasks that have the greatest impact… I implemented a daily check-in meeting.\""
 },

 ff1:{ field:"Control cards", fieldAr:"كروت الكنترول", hero:"Ahmed", icon:"🔌",
  title:"The card nobody could buy", ar:"الكارت اللي مش موجود في السوق",
  scene:"Ahmed repairs electronic control cards. A factory's production line has stopped, and the spare part doesn't exist any more.",
  words:["majored in","Do you mind if I take notes","analyzing situations and solving problems","up to him to adapt","keeps an eye on the big picture","bring to the table","putting his knowledge into practice"],
  tech:[["control card / PCB","كارت الكنترول (البوردة)"],["discontinued","اتوقف إنتاجه"],["capacitor","مكثف"],["optocoupler","أوبتوكبلر (عازل ضوئي)"],["voltage spike / surge","ارتفاع مفاجئ في الجهد"],["test bench","منصة اختبار"]],
  lines:[
   "Ahmed majored in electronics and communications. Today he repairs control cards at a maintenance company in Alexandria.",
   "One morning, a juice factory called. Their filling line had stopped. The main control card was dead, and every hour cost them 50,000 pounds.",
   "The manufacturer said, \"That card is discontinued. A new controller takes twelve weeks and costs 4,000 dollars.\"",
   "Ahmed went to the factory. Before he touched anything, he asked, \"Do you mind if I take notes while we're speaking?\"",
   "The operators told him everything: the card had failed right after a power cut.",
   "Ahmed really enjoys analyzing situations and solving problems. Back at the lab, he checked the card under a microscope.",
   "He found two swollen capacitors in the power section and a burnt optocoupler on an input channel. A voltage spike had hit the card.",
   "The factory had no drawings, so it was up to him to adapt the repair to the parts he could find in the market.",
   "He replaced the parts and tested the card for 24 hours on a test bench. The line was running again in two days — not twelve weeks.",
   "But Ahmed always keeps an eye on the big picture: \"If we don't fix the cause, the card will fail again.\" So he suggested a surge protector and a small UPS for the control panel.",
   "Then he told the factory manager, \"There's something else I can bring to the table: I can repair and test a spare card, so you always have one on the shelf.\"",
   "For Ahmed, this is the best part of the job — putting his knowledge into practice."
  ],
  qa:[
   {q:"What did Ahmed major in?", a:"He majored in electronics and communications.", opts:["Electronics","Finance"], k:0},
   {q:"What kind of factory called?", a:"A juice factory — its filling line had stopped.", opts:["A juice factory","A car factory"], k:0},
   {q:"How much did every hour cost?", a:"50,000 pounds every hour!", opts:["500 pounds","50,000 pounds"], k:1},
   {q:"Could they buy a new card?", a:"No. The card is discontinued. A new controller takes twelve weeks.", opts:["Yes, tomorrow","No, it's discontinued"], k:1},
   {q:"What did Ahmed do before he touched anything?", a:"He asked, \"Do you mind if I take notes?\" and listened to the operators.", opts:["He took notes","He replaced the card"], k:0},
   {q:"When did the card fail?", a:"Right after a power cut.", opts:["After a power cut","During lunch"], k:0},
   {q:"Does Ahmed enjoy this kind of problem?", a:"Yes! He really enjoys analyzing situations and solving problems.", opts:["Yes","No"], k:0},
   {q:"What did he find?", a:"Two swollen capacitors and a burnt optocoupler.", opts:["Swollen capacitors","A broken screen"], k:0},
   {q:"What hit the card?", a:"A voltage spike.", opts:["Water","A voltage spike"], k:1},
   {q:"Were there drawings for the card?", a:"No. It was up to him to adapt the repair to the parts in the market.", opts:["Yes, full drawings","No drawings"], k:1},
   {q:"How long did the test run?", a:"24 hours on a test bench.", opts:["24 minutes","24 hours"], k:1},
   {q:"How long was the line stopped?", a:"Two days — not twelve weeks.", opts:["Two days","Twelve weeks"], k:0},
   {q:"Why did he suggest a surge protector?", a:"He keeps an eye on the big picture — if you don't fix the cause, the card fails again.", opts:["To fix the cause","To sell more"], k:0},
   {q:"What else can he bring to the table?", a:"A repaired and tested spare card, always on the shelf.", opts:["A spare card","A new manager"], k:0}
  ],
  pov:"Now be Ahmed in an interview: \"I majored in electronics… I really enjoy analyzing situations and solving problems… It was up to me to adapt… I always keep an eye on the big picture… There's something else I can bring to the table.\""
 },

 in2:{ field:"VFDs · pumps & chillers", fieldAr:"الـ VFD للطلمبات والشيلرات", hero:"Hany", icon:"⚙️",
  title:"The pumps that were wasting money", ar:"الطلمبات اللي كانت بتحرق فلوس",
  scene:"Hany installs and repairs VFDs — variable frequency drives for big motors. He is going for a promotion, and he has stories to tell.",
  words:["proven track record of delivering results","One accomplishment that stands out","completed on time and under budget","generated a 25% increase","exceeded","new ideas are crucial for growth","align very well"],
  tech:[["VFD (variable frequency drive)","الدرايف / الإنفرتر للموتور"],["star-delta starter","بادئ ستار-دلتا"],["water hammer","ضربة المياه (المطرقة المائية)"],["overvoltage trip","فصل بسبب ارتفاع الجهد"],["deceleration time","زمن التباطؤ"],["braking resistor","مقاومة الفرملة"],["chiller / AHU","الشيلر / وحدة مناولة الهواء"]],
  lines:[
   "Hany is an applications engineer at a company that sells and repairs VFDs — variable frequency drives for big motors.",
   "He's going for a promotion to service manager, and he has a proven track record of delivering results.",
   "One accomplishment that stands out in his mind is a farm in Wadi El Natrun. Its ten irrigation pumps started at full speed with star-delta starters.",
   "Every start hit the pipes like a hammer — water hammer — and two pipes burst in one summer. The electricity bill was huge, too.",
   "Hany installed a VFD on each pump. Now the pumps start slowly and keep the pressure constant.",
   "When a pump runs 20% slower, it uses about half the power. The farm's bill fell by 35%, and no pipe burst again.",
   "The project was completed on time and under budget, and it generated a 25% increase in orders from other farms nearby.",
   "Then a hospital called. The VFDs on its chillers and big air-handling units kept tripping at night with an overvoltage fault.",
   "Hany read the fault log. The drives were stopping the huge fans too quickly, so the motors were pushing energy back into the drives.",
   "He set a longer deceleration time, added a braking resistor, and cleaned the drives' cooling fans, which were full of dust.",
   "The trips stopped, and the operating theatres stayed cool all summer. That year, his team exceeded its sales targets by 20%.",
   "Hany believes new ideas are crucial for growth. His next idea: remote monitoring for every drive, so faults are fixed before they stop a pump.",
   "His experience and skills align very well with the new role."
  ],
  qa:[
   {q:"What does Hany work with?", a:"VFDs — variable frequency drives for big motors.", opts:["VFDs","Mobile phones"], k:0},
   {q:"What role is he going for?", a:"Service manager — it's a promotion.", opts:["Service manager","Driver"], k:0},
   {q:"Does he have a good track record?", a:"Yes, a proven track record of delivering results.", opts:["Yes, a proven one","No record at all"], k:0},
   {q:"Which accomplishment stands out in his mind?", a:"The farm in Wadi El Natrun with ten irrigation pumps.", opts:["A farm","A bank"], k:0},
   {q:"How did the pumps start before?", a:"At full speed, with star-delta starters.", opts:["Slowly","At full speed"], k:1},
   {q:"What is water hammer?", a:"The hit in the pipes when a pump starts or stops too fast. Two pipes burst!", opts:["A hit in the pipes","A tool"], k:0},
   {q:"How do the pumps start with a VFD?", a:"Slowly — and the pressure stays constant.", opts:["Slowly","Suddenly"], k:0},
   {q:"If a pump runs 20% slower, how much power does it use?", a:"About half the power.", opts:["About half","The same"], k:0},
   {q:"How much did the bill fall?", a:"By 35%.", opts:["3.5%","35%"], k:1},
   {q:"Was the project late or over budget?", a:"No. It was completed on time and under budget.", opts:["Late","On time and under budget"], k:1},
   {q:"What did the project generate?", a:"A 25% increase in orders from nearby farms.", opts:["A 25% increase","More complaints"], k:0},
   {q:"What fault did the hospital drives show?", a:"An overvoltage fault — the fans were stopping too quickly.", opts:["Overvoltage","No fault"], k:0},
   {q:"How did he fix it?", a:"A longer deceleration time, a braking resistor, and clean cooling fans.", opts:["Longer deceleration time","A bigger motor"], k:0},
   {q:"Did the team hit its targets?", a:"It exceeded them by 20%!", opts:["Missed them","Exceeded them by 20%"], k:1},
   {q:"What's his next new idea?", a:"Remote monitoring for every drive — new ideas are crucial for growth.", opts:["Remote monitoring","Fewer engineers"], k:0}
  ],
  pov:"Now be Hany in his promotion interview: \"I have a proven track record of delivering results… One accomplishment that stands out in my mind… The project was completed on time and under budget… My experience and skills align very well with this role.\""
 }
};
