/* MINI STORIES — part 3: Chapter 3 (Business Meetings), one story per lesson. */
Object.assign(STORY_MORE,{
 mt1:{ field:"Maintenance contracts & collections", hero:"Karim", icon:"💸",
  title:"The month the cash ran out", ar:"الشهر اللي الفلوس خلصت فيه",
  scene:"Karim is the accounts manager at a UPS maintenance company. Clients are paying late, and there's no cash for salaries or spare parts.",
  words:["The purpose of this meeting is to address","I would like to express my gratitude for your prompt attendance","I couldn't agree more","I have a question for clarification","Let's take a moment to consider different viewpoints","Let's put that on the action item list","All in favour, raise your hands"],
  tech:[["preventive maintenance contract","عقد صيانة وقائية"],["overdue invoice","فاتورة متأخرة"],["cash flow","التدفق النقدي (السيولة)"],["aging report","تقرير أعمار الديون"],["spare parts stock","مخزون قطع الغيار"],["payment terms","شروط الدفع"]],
  lines:[
   "Karim is the accounts manager at Nile Power Care, a small company in Nasr City. They maintain UPS systems and batteries for banks and factories.",
   "It was the end of the month. Salaries were due in five days, but there was only 180,000 pounds in the bank.",
   "Clients owed the company 2.4 million pounds. Some invoices were more than 120 days overdue.",
   "Karim called an emergency meeting at nine o'clock. Everyone came on time: sales, service and purchasing.",
   "\"I would like to express my gratitude for your prompt attendance,\" he said. \"The purpose of this meeting is to address our cash problem.\"",
   "He showed the aging report. \"Our biggest client, a factory in 10th of Ramadan, owes us 900,000 pounds.\"",
   "Hany from sales said, \"We should stop visits to clients who don't pay.\" Nour from service disagreed: \"If a UPS fails at a bank, we lose the contract.\"",
   "\"Let's take a moment to consider different viewpoints,\" Karim said. \"Both of you are right.\"",
   "Samir from purchasing raised his hand. \"I have a question for clarification. Can we still buy batteries for the Alexandria job?\"",
   "\"Only with a 50% advance payment from the client,\" Karim said. \"We can't pay for their batteries with our salaries.\"",
   "Nour said, \"We need to call every client personally, not just send emails.\" \"I couldn't agree more,\" said Karim. \"Let's put that on the action item list.\"",
   "At the end, Karim proposed new payment terms: 30 days, and no new work for clients over 90 days late. \"All in favour, raise your hands.\"",
   "Every hand went up. Two weeks later, the factory paid half of its debt, and the salaries were paid on time."
  ],
  qa:[
   {q:"What does Nile Power Care do?", a:"It maintains UPS systems and batteries for banks and factories.", opts:["UPS maintenance","Car repair"], k:0},
   {q:"How much money was in the bank?", a:"Only 180,000 pounds.", opts:["2.4 million","180,000"], k:1},
   {q:"How much did clients owe?", a:"2.4 million pounds.", opts:["2.4 million pounds","24,000 pounds"], k:0},
   {q:"Did people come late to the meeting?", a:"No. Everyone came on time, so Karim said, \"I would like to express my gratitude for your prompt attendance.\"", opts:["Yes, very late","No, on time"], k:1},
   {q:"What was the purpose of the meeting?", a:"The purpose of this meeting is to address our cash problem.", opts:["A party","The cash problem"], k:1},
   {q:"Which client owed the most?", a:"A factory in 10th of Ramadan — 900,000 pounds.", opts:["A factory","A bank"], k:0},
   {q:"What did Hany want?", a:"To stop visits to clients who don't pay.", opts:["Stop visits","More visits"], k:0},
   {q:"Did Nour agree with Hany?", a:"No. If a UPS fails at a bank, they lose the contract.", opts:["Yes","No"], k:1},
   {q:"What did Karim say then?", a:"\"Let's take a moment to consider different viewpoints.\"", opts:["Consider different viewpoints","Stop talking"], k:0},
   {q:"How did Samir start his question?", a:"\"I have a question for clarification.\"", opts:["I have a question for clarification","I'm leaving"], k:0},
   {q:"Can Samir buy batteries for Alexandria?", a:"Only with a 50% advance payment from the client.", opts:["Yes, freely","Only with an advance"], k:1},
   {q:"Did Karim like Nour's idea to call clients personally?", a:"Yes! \"I couldn't agree more. Let's put that on the action item list.\"", opts:["He hated it","He couldn't agree more"], k:1},
   {q:"How did they vote on the new payment terms?", a:"Karim said, \"All in favour, raise your hands,\" and every hand went up.", opts:["Every hand went up","Nobody agreed"], k:0},
   {q:"Were the salaries paid on time?", a:"Yes. The factory paid half of its debt.", opts:["No","Yes"], k:1}
  ],
  pov:"Now be Karim opening and running the meeting: \"I would like to express my gratitude for your prompt attendance… The purpose of this meeting is to address… Let's take a moment to consider different viewpoints… I couldn't agree more… Let's put that on the action item list… All in favour, raise your hands.\""
 },

 mt2:{ field:"UPS projects", hero:"Salma", icon:"🏥",
  title:"The hospital that can't lose power", ar:"المستشفى اللي مينفعش الكهربا تقطع عنه",
  scene:"Salma is a project manager. Today is the kick-off meeting for a new 400 kVA UPS at a private hospital in Maadi.",
  words:["Allow me to introduce myself","I'd like to extend a warm welcome to our guests","Please join me in welcoming","Our objective for this meeting is to","Let's go over the agenda to make sure we're on the same page","Could you please introduce yourself and your role in the company","My apologies for running behind schedule"],
  tech:[["400 kVA UPS","يو بي إس قدرة 400 ك.ف.أ"],["battery autonomy","مدة تشغيل البطاريات (زمن الاحتياطي)"],["operating theatre","غرفة العمليات"],["site survey","معاينة الموقع"],["static bypass","المسار الجانبي (البايباس)"],["commissioning","التشغيل التجريبي والاستلام"]],
  lines:[
   "Salma is a project manager at Delta Volt Systems in Heliopolis. Her company won a contract for a 400 kVA UPS at Al Salam Care Hospital in Maadi.",
   "The kick-off meeting was at ten o'clock at the hospital. But the Ring Road was blocked, and Salma arrived fifteen minutes late.",
   "\"My apologies for running behind schedule,\" she said as she came in. \"The traffic on the Ring Road was terrible.\"",
   "\"Allow me to introduce myself. I'm Salma Adel, and I'll manage this project from start to finish.\"",
   "\"I'd like to extend a warm welcome to our guests from the hospital. Thank you for having us here.\"",
   "Then she turned to her team. \"Please join me in welcoming Eng. Tarek, our senior UPS engineer. He'll lead the installation.\"",
   "There was a man from the hospital she didn't know. \"Could you please introduce yourself and your role in the company?\" she asked.",
   "\"I'm Dr. Wael, head of the operating theatres,\" he said. \"If the power stops for one second, a patient could die.\"",
   "\"Our objective for this meeting is to agree on the plan, the dates and the risks,\" Salma said.",
   "\"Let's go over the agenda to make sure we're on the same page: the site survey, the battery autonomy, the shutdown plan and commissioning.\"",
   "Eng. Tarek explained that the batteries would give fifteen minutes of autonomy, enough time for the generators to start.",
   "Dr. Wael had one condition: no work during operations. So they agreed to switch to the new UPS on a Friday at 6 a.m., using the static bypass.",
   "Everyone left the meeting on the same page. And the next time, Salma left home an hour early."
  ],
  qa:[
   {q:"Where does Salma work?", a:"At Delta Volt Systems in Heliopolis.", opts:["Delta Volt Systems","The hospital"], k:0},
   {q:"How big is the new UPS?", a:"400 kVA.", opts:["40 kVA","400 kVA"], k:1},
   {q:"Was Salma on time?", a:"No, she was fifteen minutes late because of the Ring Road.", opts:["Yes","No, fifteen minutes late"], k:1},
   {q:"What did she say when she arrived?", a:"\"My apologies for running behind schedule.\"", opts:["My apologies for running behind schedule","Let's start"], k:0},
   {q:"How did she introduce herself?", a:"\"Allow me to introduce myself. I'm Salma Adel.\"", opts:["Allow me to introduce myself","Who are you?"], k:0},
   {q:"What did she say to the hospital people?", a:"\"I'd like to extend a warm welcome to our guests.\"", opts:["Please be quiet","A warm welcome to our guests"], k:1},
   {q:"Who is Eng. Tarek?", a:"Their senior UPS engineer. \"Please join me in welcoming Eng. Tarek.\"", opts:["A doctor","The senior UPS engineer"], k:1},
   {q:"What did she ask Dr. Wael?", a:"\"Could you please introduce yourself and your role in the company?\"", opts:["His role","His salary"], k:0},
   {q:"What is Dr. Wael's job?", a:"He's the head of the operating theatres.", opts:["Head of operating theatres","Hospital accountant"], k:0},
   {q:"What was the objective of the meeting?", a:"Our objective for this meeting is to agree on the plan, the dates and the risks.", opts:["To sign the invoice","To agree on the plan"], k:1},
   {q:"Why did she go over the agenda?", a:"To make sure they're all on the same page.", opts:["To be on the same page","To save paper"], k:0},
   {q:"How much battery autonomy will they have?", a:"Fifteen minutes — enough for the generators to start.", opts:["Fifteen minutes","Five hours"], k:0},
   {q:"When will they switch to the new UPS?", a:"On a Friday at 6 a.m., using the static bypass.", opts:["During an operation","Friday at 6 a.m."], k:1}
  ],
  pov:"Now be Salma at the kick-off: \"My apologies for running behind schedule… Allow me to introduce myself… I'd like to extend a warm welcome to our guests… Please join me in welcoming… Could you please introduce yourself and your role in the company?… Our objective for this meeting is to… Let's go over the agenda to make sure we're on the same page.\""
 },

 mt3:{ field:"Field service", hero:"Youssef", icon:"🔧",
  title:"The engineer who loved football", ar:"المهندس اللي بيحب الكورة",
  scene:"Youssef leads the weekly service-team meeting. One engineer, Sherif, keeps talking about everything except the agenda.",
  words:["Can I have your input on this matter","I'll now turn the floor over to","Could you elaborate on that a bit more, please","Shall we proceed to the next item on the agenda","Let's not get sidetracked","Can we hold that thought for a moment and come back to it later","I'm on board with that"],
  tech:[["service ticket","بلاغ صيانة (تذكرة)"],["capacitor","مكثف"],["VFD (variable frequency drive)","الإنفرتر (مغير السرعة)"],["overheating fault","عطل ارتفاع الحرارة"],["cooling fan","مروحة التبريد"],["response time","زمن الاستجابة"]],
  lines:[
   "Every Sunday morning, Youssef runs the service-team meeting at Power Hub Egypt in 6th of October City.",
   "The first item was a VFD at a water station in Giza. It stopped three times last week with an overheating fault.",
   "\"Sherif, you visited the site. Can I have your input on this matter?\" Youssef asked.",
   "Sherif started well. \"The cooling fan was dusty.\" Then he said, \"By the way, did you see the Ahly match yesterday?\"",
   "\"Let's not get sidetracked,\" Youssef said with a smile. \"Could you elaborate on that a bit more, please? Just the fan.\"",
   "Sherif explained that the fan was full of sand, and the heatsink was at 85 degrees. He cleaned it, and the drive was fine.",
   "\"Shall we proceed to the next item on the agenda?\" Youssef said. \"Our response time to service tickets.\"",
   "\"I'll now turn the floor over to Mariam. She has the numbers.\" Mariam said the average response time was nine hours. The target is four.",
   "Sherif jumped in again: \"We need a new company car! And a coffee machine! And a bigger office!\"",
   "\"Good points, Sherif. Can we hold that thought for a moment and come back to it later?\" Youssef asked.",
   "Mariam suggested one engineer on standby every evening, with a spare-parts box of capacitors and fans in his car.",
   "\"I'm on board with that,\" Youssef said. Even Sherif agreed. \"I'm on board with that too — if I get the car!\"",
   "Everyone laughed. At the end, Youssef came back to the car. It was added to the budget request."
  ],
  qa:[
   {q:"When is the service-team meeting?", a:"Every Sunday morning.", opts:["Every Sunday","Every Friday"], k:0},
   {q:"What was the problem at the water station?", a:"A VFD stopped three times with an overheating fault.", opts:["A broken pump","An overheating VFD"], k:1},
   {q:"What did Youssef ask Sherif?", a:"\"Can I have your input on this matter?\"", opts:["Can I have your input on this matter?","Why are you late?"], k:0},
   {q:"What did Sherif start talking about?", a:"The Ahly match!", opts:["The Ahly match","The invoice"], k:0},
   {q:"What did Youssef say then?", a:"\"Let's not get sidetracked.\"", opts:["Tell me more about football","Let's not get sidetracked"], k:1},
   {q:"Did Youssef want more details about the fan?", a:"Yes: \"Could you elaborate on that a bit more, please?\"", opts:["No","Yes"], k:1},
   {q:"What was inside the fan?", a:"Sand. The heatsink was at 85 degrees.", opts:["Water","Sand"], k:1},
   {q:"How did Youssef move on?", a:"\"Shall we proceed to the next item on the agenda?\"", opts:["Shall we proceed to the next item?","Let's go home"], k:0},
   {q:"Who talked about response time?", a:"Mariam. \"I'll now turn the floor over to Mariam.\"", opts:["Sherif","Mariam"], k:1},
   {q:"What is the average response time?", a:"Nine hours. The target is four.", opts:["Nine hours","Four hours"], k:0},
   {q:"What did Sherif ask for?", a:"A new car, a coffee machine and a bigger office.", opts:["A holiday","A new car"], k:1},
   {q:"What did Youssef say about the car?", a:"\"Can we hold that thought for a moment and come back to it later?\"", opts:["Hold that thought","No, never"], k:0},
   {q:"Did Youssef like Mariam's standby idea?", a:"Yes. \"I'm on board with that.\"", opts:["He's on board with that","He refused"], k:0},
   {q:"Did they forget the car?", a:"No. Youssef came back to it, and it went into the budget request.", opts:["Yes","No"], k:1}
  ],
  pov:"Now be Youssef running the meeting: \"Can I have your input on this matter?… Let's not get sidetracked… Could you elaborate on that a bit more, please?… Shall we proceed to the next item on the agenda?… I'll now turn the floor over to… Can we hold that thought for a moment and come back to it later?… I'm on board with that.\""
 },

 mt4:{ field:"Sales & pricing", hero:"Hoda", icon:"🧮",
  title:"The 25% discount", ar:"خصم الـ 25%",
  scene:"Hoda is a sales engineer. Her manager wants to give a data-centre client a huge discount, and she doesn't think it's a good idea.",
  words:["I see your point, but I have a different perspective","I have reservations about that proposal","I didn't catch the last part. Would you mind repeating it","I'm sorry to interrupt, but I have a quick question","If I may, I'd like to interject with a suggestion","I'd like to bring up an additional point","I regret to inform you that I won't be able to attend the meeting"],
  tech:[["server rack","راك سيرفرات (دولاب سيرفرات)"],["precision cooling","تكييف دقيق (للداتا سنتر)"],["profit margin","هامش الربح"],["quotation","عرض سعر"],["annual maintenance contract (AMC)","عقد صيانة سنوي"],["lithium-ion battery","بطارية ليثيوم أيون"]],
  lines:[
   "Hoda is a sales engineer at Cairo Data Power. She prepared a quotation for a new data-centre room at a bank in the New Administrative Capital: server racks, two UPS systems, lithium-ion batteries and precision cooling.",
   "The total was 6.8 million pounds, with a profit margin of 18%.",
   "The night before the pricing meeting, Ahmed from accounts sent an email: \"I regret to inform you that I won't be able to attend the meeting. My daughter is in hospital.\"",
   "In the meeting, her manager, Mr. Ashraf, spoke fast. \"The bank is a big name. Let's give them 25% off, and…\" His phone rang, and his voice was lost.",
   "\"I didn't catch the last part. Would you mind repeating it?\" Hoda asked.",
   "\"I said: 25% off, and we'll win the next three branches too.\"",
   "Hoda took a breath. \"I see your point, but I have a different perspective. With 25% off, we lose 7% on every rack. We'd pay the bank to work for them.\"",
   "\"I have reservations about that proposal,\" she continued. \"And there's no contract for the three branches. It's only a promise.\"",
   "Mr. Ashraf began to write numbers on the board. \"I'm sorry to interrupt, but I have a quick question,\" Hoda said. \"Did the bank ask for a discount, or is it our idea?\"",
   "He stopped. \"Well… they only said the price was a little high.\"",
   "\"If I may, I'd like to interject with a suggestion. Let's give 7% off, and add a free first-year maintenance contract.\"",
   "\"I'd like to bring up an additional point,\" she said. \"The AMC after year one brings us 400,000 pounds every year.\"",
   "Mr. Ashraf thought for a minute and agreed. The bank accepted the offer — and Hoda sent the minutes to Ahmed at the hospital."
  ],
  qa:[
   {q:"Where does Hoda work?", a:"At Cairo Data Power. She's a sales engineer.", opts:["Cairo Data Power","The bank"], k:0},
   {q:"What was the total of her quotation?", a:"6.8 million pounds.", opts:["6.8 million","680,000"], k:0},
   {q:"Why didn't Ahmed attend?", a:"His daughter was in hospital. He wrote, \"I regret to inform you that I won't be able to attend the meeting.\"", opts:["He was on holiday","His daughter was in hospital"], k:1},
   {q:"Why didn't Hoda hear her manager?", a:"His phone rang. So she said, \"I didn't catch the last part. Would you mind repeating it?\"", opts:["His phone rang","She was asleep"], k:0},
   {q:"How much discount did Mr. Ashraf want?", a:"25%.", opts:["7%","25%"], k:1},
   {q:"Did Hoda agree?", a:"No. \"I see your point, but I have a different perspective.\"", opts:["Yes, completely","No, she had a different perspective"], k:1},
   {q:"What happens with 25% off?", a:"They lose 7% on every rack.", opts:["They lose money","They make more money"], k:0},
   {q:"What did she say about the proposal?", a:"\"I have reservations about that proposal.\"", opts:["I love it","I have reservations"], k:1},
   {q:"Was there a contract for three more branches?", a:"No, only a promise.", opts:["Yes","No, only a promise"], k:1},
   {q:"How did she stop him to ask her question?", a:"\"I'm sorry to interrupt, but I have a quick question.\"", opts:["I'm sorry to interrupt","Be quiet"], k:0},
   {q:"Did the bank ask for the discount?", a:"No. They only said the price was a little high.", opts:["Yes","No"], k:1},
   {q:"What was Hoda's suggestion?", a:"7% off and a free first-year maintenance contract.", opts:["7% off plus free AMC","50% off"], k:0},
   {q:"What was her additional point?", a:"The AMC after year one brings 400,000 pounds every year.", opts:["The AMC income","The weather"], k:0},
   {q:"Did the bank accept?", a:"Yes, the bank accepted the offer.", opts:["No","Yes"], k:1}
  ],
  pov:"Now be Hoda in the meeting: \"I didn't catch the last part. Would you mind repeating it?… I see your point, but I have a different perspective… I have reservations about that proposal… I'm sorry to interrupt, but I have a quick question… If I may, I'd like to interject with a suggestion… I'd like to bring up an additional point.\" Then be Ahmed: \"I regret to inform you that I won't be able to attend the meeting.\""
 },

 mt5:{ field:"Solar plants & purchasing", hero:"Mahmoud", icon:"☀️",
  title:"The inverter vote", ar:"التصويت على الإنفرتر",
  scene:"Mahmoud is a purchasing engineer. He has to move a supplier meeting, then help his team choose an inverter brand for a new solar plant.",
  words:["I apologize, but I will have to reschedule our meeting","The meeting needs to be postponed","Please let me know which option works best for everyone","Shall we put it to a vote","Can we get a show of hands","Let's take a moment to summarize the key takeaways and decisions made today","That concludes our meeting for today"],
  tech:[["solar inverter","إنفرتر الطاقة الشمسية"],["PV panel","لوح شمسي (خلية فوتوفولتية)"],["on-grid system","نظام متصل بالشبكة"],["efficiency","الكفاءة"],["warranty","الضمان"],["lead time","مدة التوريد"]],
  lines:[
   "Mahmoud is a purchasing engineer at SunRise Energy Solutions in Mansoura. His company is building a 1 MW on-grid solar plant on a farm near Beni Suef.",
   "On Tuesday, he had a meeting with an inverter supplier from Alexandria. But on Monday, the client called an urgent site visit for Tuesday.",
   "Mahmoud wrote an email: \"Dear Mr. Fathy, I apologize, but I will have to reschedule our meeting. The meeting needs to be postponed because of an urgent site visit.\"",
   "\"I can do Wednesday at 11 or Thursday at 2. Please let me know which option works best for everyone.\"",
   "Mr. Fathy chose Thursday. On Thursday, after his visit, Mahmoud met his own team to choose the inverter brand.",
   "There were two options. Brand A had 98.6% efficiency and a ten-year warranty, but the lead time was twelve weeks.",
   "Brand B had 98.2% efficiency and a five-year warranty, but it was in stock in Cairo and 15% cheaper.",
   "Laila from sales wanted Brand B because the client wanted the plant running before summer. Omar from service wanted Brand A because of the warranty.",
   "After thirty minutes of discussion, Mahmoud said, \"Shall we put it to a vote?\"",
   "\"Can we get a show of hands for Brand A?\" Three hands. \"And Brand B?\" Four hands. Brand B won.",
   "\"Let's take a moment to summarize the key takeaways and decisions made today,\" Mahmoud said.",
   "\"We choose Brand B. I'll ask the supplier for a free extra five years of warranty. Omar will train the technicians. The plant will run before June.\"",
   "\"Thank you, everyone. That concludes our meeting for today.\" And Mr. Fathy, the supplier, finally got his order."
  ],
  qa:[
   {q:"What is Mahmoud's job?", a:"He's a purchasing engineer at SunRise Energy Solutions.", opts:["Purchasing engineer","Driver"], k:0},
   {q:"How big is the solar plant?", a:"1 MW, on a farm near Beni Suef.", opts:["1 MW","10 kW"], k:0},
   {q:"Why did he move the supplier meeting?", a:"Because of an urgent site visit on Tuesday.", opts:["He was sick","An urgent site visit"], k:1},
   {q:"What did he write to Mr. Fathy?", a:"\"I apologize, but I will have to reschedule our meeting.\"", opts:["I will have to reschedule our meeting","I'm cancelling the order"], k:0},
   {q:"Was the meeting cancelled forever?", a:"No. The meeting needs to be postponed, not cancelled.", opts:["Yes","No, just postponed"], k:1},
   {q:"How did he offer the new times?", a:"\"Please let me know which option works best for everyone.\"", opts:["Which option works best","Come whenever"], k:0},
   {q:"Which day did Mr. Fathy choose?", a:"Thursday.", opts:["Wednesday","Thursday"], k:1},
   {q:"Which brand had the longer warranty?", a:"Brand A — ten years.", opts:["Brand A","Brand B"], k:0},
   {q:"Why did Laila want Brand B?", a:"It was in stock, and the client wanted the plant running before summer.", opts:["It's in stock","It's prettier"], k:0},
   {q:"How did Mahmoud end the discussion?", a:"\"Shall we put it to a vote?\"", opts:["Let's go home","Shall we put it to a vote?"], k:1},
   {q:"How did they vote?", a:"\"Can we get a show of hands?\" Three for A, four for B.", opts:["By secret paper","A show of hands"], k:1},
   {q:"Which brand won?", a:"Brand B, four to three.", opts:["Brand A","Brand B"], k:1},
   {q:"What did Mahmoud do before closing?", a:"\"Let's take a moment to summarize the key takeaways and decisions made today.\"", opts:["Summarized the decisions","Ordered lunch"], k:0},
   {q:"How did he close the meeting?", a:"\"That concludes our meeting for today.\"", opts:["That concludes our meeting for today","See you tomorrow night"], k:0}
  ],
  pov:"Now be Mahmoud: write the email — \"I apologize, but I will have to reschedule our meeting. The meeting needs to be postponed… Please let me know which option works best for everyone.\" Then run the team meeting: \"Shall we put it to a vote?… Can we get a show of hands?… Let's take a moment to summarize the key takeaways and decisions made today… That concludes our meeting for today.\""
 }
});
