/* MINI STORIES — part 4: Chapter 4 (Presenting), one story per lesson. */
Object.assign(STORY_MORE,{
 pr1:{ field:"UPS Maintenance Contracts", hero:"Rana", icon:"🏥",
  title:"The honest detail", ar:"التفصيلة اللي اتقالت بصراحة",
  scene:"Rana sells UPS maintenance contracts. Today she presents one to a hospital board — and almost forgets something important.",
  words:["Our agenda today will cover four main topics","As you can see from this graph","Moving on to the second topic","We pride ourselves on offering personalized solutions","There are no hidden fees or charges","I want to apologize for not mentioning an important detail","If you have any further questions, please do not hesitate to ask me"],
  tech:[["maintenance contract","عقد صيانة"],["backup time","وقت التشغيل الاحتياطي على البطاريات"],["mains failure","انقطاع كهربا الشبكة"],["operating theatre","أوضة العمليات"],["capacitor","مكثف (كباستور)"],["battery replacement","تغيير البطاريات"]],
  lines:[
   "Rana is a sales engineer at VoltGuard, a company in Nasr City that sells and maintains UPS systems.",
   "Today she is presenting a maintenance contract to the board of Nile Care Hospital in Mansoura.",
   "\"Good morning, everyone. Our agenda today will cover four main topics: your UPS systems, the risks, our contract, and the price.\"",
   "She showed a graph of the hospital's three 120 kVA UPS units. \"As you can see from this graph, the backup time has dropped from twenty minutes to eight.\"",
   "\"Moving on to the second topic: the risks. If there is a mains failure and the batteries are weak, the operating theatres could lose power.\"",
   "\"We pride ourselves on offering personalized solutions. For a hospital, that means a visit every three months and an engineer on call 24/7.\"",
   "Dr. Hesham, the hospital's finance manager, asked about the cost.",
   "\"The contract is 180,000 pounds a year. There are no hidden fees or charges — fans and capacitors are included.\"",
   "Suddenly Rana stopped. She had forgotten something.",
   "\"I want to apologize for not mentioning an important detail. Battery replacement is not included. We quote it separately.\"",
   "The board members liked her honesty. Dr. Hesham nodded and wrote a note.",
   "\"If you have any further questions, please do not hesitate to ask me,\" Rana said with a smile.",
   "One week later, the hospital signed the contract."
  ],
  qa:[
   {q:"Where does Rana work?", a:"At VoltGuard, a UPS company in Nasr City.", opts:["At a hospital","At VoltGuard"], k:1},
   {q:"Who is she presenting to?", a:"The board of Nile Care Hospital in Mansoura.", opts:["A hospital board","A school"], k:0},
   {q:"How did she start?", a:"\"Our agenda today will cover four main topics.\"", opts:["With four main topics","With a joke"], k:0},
   {q:"How many UPS units does the hospital have?", a:"Three 120 kVA units.", opts:["Three","Thirteen"], k:0},
   {q:"What did she say about the graph?", a:"\"As you can see from this graph, the backup time has dropped.\"", opts:["The backup time went up","The backup time dropped"], k:1},
   {q:"What is the backup time now?", a:"Only eight minutes.", opts:["Twenty minutes","Eight minutes"], k:1},
   {q:"What was the second topic?", a:"\"Moving on to the second topic: the risks.\"", opts:["The price","The risks"], k:1},
   {q:"What could happen in a mains failure?", a:"The operating theatres could lose power.", opts:["They could lose power","Nothing"], k:0},
   {q:"What does VoltGuard pride itself on?", a:"\"We pride ourselves on offering personalized solutions.\"", opts:["Cheap prices","Personalized solutions"], k:1},
   {q:"How often will an engineer visit?", a:"Every three months.", opts:["Every three months","Every three years"], k:0},
   {q:"How much is the contract?", a:"180,000 pounds a year.", opts:["180,000 pounds","18,000 pounds"], k:0},
   {q:"Are there extra costs for fans and capacitors?", a:"No. \"There are no hidden fees or charges.\"", opts:["Yes","No hidden fees"], k:1},
   {q:"What did Rana forget?", a:"\"I want to apologize for not mentioning an important detail\" — battery replacement is not included.", opts:["Battery replacement","Her laptop"], k:0},
   {q:"How did she close?", a:"\"If you have any further questions, please do not hesitate to ask me.\"", opts:["Please do not hesitate to ask me","Please leave now"], k:0}
  ],
  pov:"Now be Rana in front of the board: \"Our agenda today will cover four main topics… As you can see from this graph… Moving on to the second topic… We pride ourselves on offering personalized solutions… There are no hidden fees or charges… I want to apologize for not mentioning an important detail… If you have any further questions, please do not hesitate to ask me.\""
 },
 pr2:{ field:"Lithium-ion Batteries", hero:"Tarek", icon:"🔋",
  title:"Tired technicians, lithium cells", ar:"فنيين تعبانين وخلايا ليثيوم",
  scene:"Tarek opens a one-day training on lithium-ion batteries for technicians who travelled all night.",
  words:["Thank you for taking the time to join us today","I know everyone's time is valuable","The objective of today's presentation is to","By the end of this presentation, you will have a clear understanding of","I'll be breaking the presentation down into three parts","please feel free to raise your hand and ask","if you could hold your questions until the end"],
  tech:[["lithium-ion battery","بطارية ليثيوم أيون"],["BMS (battery management system)","نظام إدارة البطارية"],["cell","خلية"],["charging voltage","جهد الشحن"],["battery cabinet","كابينة بطاريات"],["to trip","يفصل (يقطع)"]],
  lines:[
   "Tarek is the senior battery engineer at VoltGuard. Today he is training fifteen technicians in the company's workshop in 6th of October City.",
   "Some of them came from Alexandria and Assiut early in the morning, and they looked tired.",
   "\"Thank you for taking the time to join us today. I know everyone's time is valuable, so we'll finish before three o'clock.\"",
   "\"The objective of today's presentation is to show you how to install and service lithium-ion batteries safely.\"",
   "\"By the end of this presentation, you will have a clear understanding of the BMS and how it protects every cell.\"",
   "\"I'll be breaking the presentation down into three parts: safety, installation, and troubleshooting.\"",
   "\"In the safety part, please feel free to raise your hand and ask. Safety questions can't wait.\"",
   "Youssef from Assiut raised his hand. \"Can we use the old lead-acid charging settings on the UPS?\"",
   "\"Good question — no! The charging voltage is different. Wrong settings can damage the cells or make the BMS trip.\"",
   "In the second part, Tarek connected a real battery cabinet to a 60 kVA UPS and showed the BMS screen.",
   "\"This part is long, so if you could hold your questions until the end, we'll have twenty minutes for them.\"",
   "At the end, the technicians had many questions — and nobody looked tired anymore."
  ],
  qa:[
   {q:"What is Tarek's job?", a:"He's the senior battery engineer at VoltGuard.", opts:["Battery engineer","Accountant"], k:0},
   {q:"How many technicians are there?", a:"Fifteen.", opts:["Five","Fifteen"], k:1},
   {q:"Why did some technicians look tired?", a:"They came from Alexandria and Assiut early in the morning.", opts:["They travelled early","They were sick"], k:0},
   {q:"How did Tarek thank them?", a:"\"Thank you for taking the time to join us today.\"", opts:["Thank you for taking the time","Thanks for nothing"], k:0},
   {q:"Why will they finish before three?", a:"\"I know everyone's time is valuable.\"", opts:["The power will go off","Everyone's time is valuable"], k:1},
   {q:"What is the objective of the presentation?", a:"\"The objective of today's presentation is to show you how to install and service lithium-ion batteries safely.\"", opts:["Selling batteries","Installing lithium batteries safely"], k:1},
   {q:"What will they understand by the end?", a:"\"By the end of this presentation, you will have a clear understanding of the BMS.\"", opts:["The BMS","The price list"], k:0},
   {q:"How many parts is the presentation?", a:"\"I'll be breaking the presentation down into three parts.\"", opts:["Two","Three"], k:1},
   {q:"What are the three parts?", a:"Safety, installation, and troubleshooting.", opts:["Safety, installation, troubleshooting","Sales, marketing, finance"], k:0},
   {q:"What can they do in the safety part?", a:"\"Please feel free to raise your hand and ask.\"", opts:["Raise their hand and ask","Sleep"], k:0},
   {q:"Can they use the old lead-acid settings?", a:"No! The charging voltage is different.", opts:["Yes","No"], k:1},
   {q:"What can wrong settings do?", a:"Damage the cells or make the BMS trip.", opts:["Nothing","Damage the cells"], k:1},
   {q:"What did he ask in the second part?", a:"\"If you could hold your questions until the end…\"", opts:["Ask now","Hold questions until the end"], k:1}
  ],
  pov:"Now be Tarek opening the training: \"Thank you for taking the time to join us today. I know everyone's time is valuable… The objective of today's presentation is to… By the end of this presentation, you will have a clear understanding of… I'll be breaking the presentation down into three parts… Please feel free to raise your hand and ask… If you could hold your questions until the end…\""
 },
 pr3:{ field:"Service & Spare Parts", hero:"Sherif", icon:"📊",
  title:"Eyes on the screen", ar:"العيون على الشاشة",
  scene:"Sherif presents the service department's quarterly results, but half the room is looking at their phones.",
  words:["Let's begin by looking at our first main point","Now, I'd like to talk about","If anyone needs to step out, please feel free to do so","I'd like to draw your attention to the screen","As I mentioned earlier","To build on that","Please let me know if anything is unclear"],
  tech:[["maintenance visit","زيارة صيانة"],["response time","زمن الاستجابة"],["cooling alarm","إنذار التبريد"],["spare parts","قطع الغيار"],["VFD board","كارت ‎VFD‎"],["local stock","مخزون محلي"]],
  lines:[
   "Sherif is the service manager at VoltGuard. Every quarter, he presents the service department's results to the managers.",
   "This morning, the meeting room in Heliopolis was full, but many people were looking at their phones.",
   "\"Let's begin by looking at our first main point: we completed 340 maintenance visits this quarter, 15% more than last quarter.\"",
   "\"Now, I'd like to talk about our response time. For UPS failures in Cairo, it's now under four hours.\"",
   "Just then, Amr's phone rang. A client's data centre in Smart Village had a cooling alarm.",
   "\"If anyone needs to step out, please feel free to do so,\" Sherif said calmly. Amr left the room.",
   "The others were still reading emails, so Sherif changed his tone.",
   "\"I'd like to draw your attention to the screen. This red bar shows our biggest problem: late spare parts.\"",
   "\"Some VFD boards took six weeks to arrive from Europe. As I mentioned earlier, our response time is fast — but without parts, the repair is slow.\"",
   "\"To build on that, we suggest keeping a local stock of the ten most common parts in our Obour warehouse.\"",
   "Now everyone was looking at the screen. The general manager asked about the cost of the stock.",
   "\"About two million pounds,\" Sherif answered. \"Please let me know if anything is unclear.\"",
   "Nobody touched their phone again until the end."
  ],
  qa:[
   {q:"What does Sherif present every quarter?", a:"The service department's results.", opts:["The service results","The football results"], k:0},
   {q:"What were many people doing?", a:"Looking at their phones.", opts:["Taking notes","Looking at their phones"], k:1},
   {q:"How did he begin?", a:"\"Let's begin by looking at our first main point.\"", opts:["Our first main point","Our last point"], k:0},
   {q:"How many maintenance visits did they complete?", a:"340 — 15% more than last quarter.", opts:["340","34"], k:0},
   {q:"What did he talk about next?", a:"\"Now, I'd like to talk about our response time.\"", opts:["Salaries","Response time"], k:1},
   {q:"What is the response time in Cairo?", a:"Under four hours.", opts:["Under four hours","Four days"], k:0},
   {q:"Why did Amr's phone ring?", a:"A data centre in Smart Village had a cooling alarm.", opts:["A cooling alarm","His birthday"], k:0},
   {q:"What did Sherif tell him?", a:"\"If anyone needs to step out, please feel free to do so.\"", opts:["Sit down!","Feel free to step out"], k:1},
   {q:"How did he get the others to look up?", a:"\"I'd like to draw your attention to the screen.\"", opts:["He shouted","He drew attention to the screen"], k:1},
   {q:"What does the red bar show?", a:"Late spare parts — their biggest problem.", opts:["Late spare parts","High salaries"], k:0},
   {q:"How long did some VFD boards take?", a:"Six weeks, from Europe.", opts:["Six days","Six weeks"], k:1},
   {q:"What did he repeat from before?", a:"\"As I mentioned earlier, our response time is fast.\"", opts:["Response time is fast","Prices are high"], k:0},
   {q:"What did he suggest?", a:"\"To build on that\" — a local stock of parts in Obour.", opts:["A local stock","A new office"], k:0},
   {q:"How did he finish?", a:"\"Please let me know if anything is unclear.\"", opts:["Let me know if anything is unclear","Turn off your phones"], k:0}
  ],
  pov:"Now be Sherif in the meeting room: \"Let's begin by looking at our first main point… Now, I'd like to talk about… If anyone needs to step out, please feel free to do so… I'd like to draw your attention to the screen… As I mentioned earlier… To build on that… Please let me know if anything is unclear.\""
 },
 pr4:{ field:"Solar & Battery Storage", hero:"Laila", icon:"☀️",
  title:"Numbers, not dreams", ar:"أرقام مش أحلام",
  scene:"Laila has fifteen minutes to convince a tough finance director that solar plus batteries will save money.",
  words:["Let me walk you through this chart","There has been a significant increase in this area","These numbers paint a clear picture of the current situation","It's a well-known fact that","Research has shown that","To put this in context, let me give you an example","I want to open the floor for any questions or comments"],
  tech:[["solar plant","محطة طاقة شمسية"],["battery storage","تخزين بالبطاريات"],["inverter","إنفرتر (محوّل)"],["payback period","فترة استرداد التكلفة"],["remote monitoring","مراقبة عن بُعد"],["site survey","معاينة الموقع"]],
  lines:[
   "Laila is a solar engineer at VoltGuard. Today she is meeting Mr. Adel, the finance director of Delta Pack, a packaging factory in 10th of Ramadan City.",
   "Mr. Adel likes numbers, not dreams. \"You have fifteen minutes,\" he said.",
   "\"Let me walk you through this chart. The blue line is your monthly electricity bill for the last three years.\"",
   "\"There has been a significant increase in this area. Your bill went from 400,000 to 950,000 pounds a month.\"",
   "\"These numbers paint a clear picture of the current situation: energy is now your third biggest cost.\"",
   "\"It's a well-known fact that Egypt has some of the best sunshine in the world. And your factory roof is 12,000 square metres — and empty.\"",
   "\"Research has shown that a solar plant with battery storage can cut a factory's electricity bill by 30 to 40 percent.\"",
   "\"To put this in context, let me give you an example. Last year we built a 1 MW solar plant for a textile factory in Sadat City.\"",
   "\"With batteries, their machines also keep running during short power cuts. Their payback period was under five years.\"",
   "Mr. Adel studied the chart again. \"And who maintains the inverters and batteries?\"",
   "\"We do. The offer includes a five-year contract with remote monitoring.\"",
   "\"I want to open the floor for any questions or comments,\" Laila said, looking at the whole team.",
   "Mr. Adel smiled for the first time. \"Just one question: when can you start the site survey?\""
  ],
  qa:[
   {q:"Who is Mr. Adel?", a:"The finance director of Delta Pack.", opts:["The finance director","The driver"], k:0},
   {q:"What does Mr. Adel like?", a:"Numbers, not dreams.", opts:["Dreams","Numbers"], k:1},
   {q:"How much time did Laila have?", a:"Fifteen minutes.", opts:["Fifteen minutes","Fifty minutes"], k:0},
   {q:"How did she start with the chart?", a:"\"Let me walk you through this chart.\"", opts:["Let me walk you through this chart","Let me skip this chart"], k:0},
   {q:"What does the blue line show?", a:"The factory's monthly electricity bill.", opts:["Sales","The electricity bill"], k:1},
   {q:"What happened to the bill?", a:"\"There has been a significant increase in this area\" — from 400,000 to 950,000 pounds.", opts:["A big increase","A small decrease"], k:0},
   {q:"What picture do the numbers paint?", a:"\"These numbers paint a clear picture of the current situation.\"", opts:["A clear picture","A funny picture"], k:0},
   {q:"What is a well-known fact about Egypt?", a:"\"It's a well-known fact that Egypt has some of the best sunshine in the world.\"", opts:["Lots of rain","The best sunshine"], k:1},
   {q:"How big is the factory roof?", a:"12,000 square metres.", opts:["1,200 m²","12,000 m²"], k:1},
   {q:"What has research shown?", a:"\"Research has shown that\" solar with batteries can cut the bill by 30 to 40 percent.", opts:["A 30–40% cut","A 3–4% cut"], k:0},
   {q:"What example did she give?", a:"\"To put this in context, let me give you an example\" — a 1 MW plant in Sadat City.", opts:["A textile factory","A hotel"], k:0},
   {q:"What was their payback period?", a:"Under five years.", opts:["Under five years","Over fifteen years"], k:0},
   {q:"How did Laila end?", a:"\"I want to open the floor for any questions or comments.\"", opts:["I want to open the floor","I want to go home"], k:0},
   {q:"What was Mr. Adel's question?", a:"When can you start the site survey?", opts:["Why so expensive?","When can you start?"], k:1}
  ],
  pov:"Now be Laila with the finance director: \"Let me walk you through this chart… There has been a significant increase in this area… These numbers paint a clear picture of the current situation… It's a well-known fact that… Research has shown that… To put this in context, let me give you an example… I want to open the floor for any questions or comments.\""
 },
 pr5:{ field:"Data Centres & Tenders", hero:"Hossam", icon:"🏆",
  title:"The last ten minutes", ar:"آخر عشر دقايق",
  scene:"Hossam closes a big data-centre tender presentation. He loses his place once, then faces a tough question about price.",
  words:["To recap, we discussed","After careful consideration, our team recommends","Based on the data, we recommend that","Sorry, I seem to have lost my train of thought","I'd like to open the floor for any questions you may have","Did that answer your question?","Thank you all for your attention and time today"],
  tech:[["tender","مناقصة"],["modular UPS","‎UPS‎ موديولار"],["N+1 redundancy","احتياطي ‎N+1‎"],["downtime","وقت التوقف"],["total cost of ownership","التكلفة الإجمالية على مدار العمر"],["committee","لجنة"]],
  lines:[
   "Hossam is the tender manager at VoltGuard. Today is the final presentation for a new data centre for Nile Digital Bank in the New Administrative Capital.",
   "The bank's committee has seven members, and three companies are competing for the project.",
   "\"To recap, we discussed the power design, the cooling, and the installation plan for the server rooms.\"",
   "\"After careful consideration, our team recommends two 500 kVA modular UPS systems with lithium-ion batteries.\"",
   "\"Based on the data, we recommend that you choose N+1 redundancy, so one module can fail without any downtime.\"",
   "Then he looked at his notes and stopped. \"The battery life is… Sorry, I seem to have lost my train of thought.\"",
   "He took a breath, found the right slide, and continued: \"The battery life is fifteen years — twice as long as lead-acid.\"",
   "\"I'd like to open the floor for any questions you may have.\"",
   "Eng. Samia, the head of the committee, asked a tough question: \"Your price is 12% higher than another offer. Why should we pay more?\"",
   "\"Because you won't need to replace the batteries every five years. Over fifteen years, our total cost of ownership is 8% lower.\"",
   "\"Did that answer your question?\" Hossam asked. \"Yes, very clearly,\" Samia said.",
   "\"Thank you all for your attention and time today,\" he said, and closed his laptop.",
   "Two weeks later, VoltGuard won the tender."
  ],
  qa:[
   {q:"What is Hossam's job?", a:"He's the tender manager at VoltGuard.", opts:["Tender manager","Security guard"], k:0},
   {q:"Where will the data centre be?", a:"In the New Administrative Capital.", opts:["In Aswan","In the New Administrative Capital"], k:1},
   {q:"How many companies are competing?", a:"Three.", opts:["Three","Seven"], k:0},
   {q:"How did he start his closing?", a:"\"To recap, we discussed the power design, the cooling, and the installation plan.\"", opts:["To recap, we discussed…","Let's start again"], k:0},
   {q:"What does his team recommend?", a:"\"After careful consideration, our team recommends two 500 kVA modular UPS systems.\"", opts:["Diesel generators","Two modular UPS systems"], k:1},
   {q:"Why N+1 redundancy?", a:"\"Based on the data, we recommend that\" — so one module can fail without downtime.", opts:["To save space","So there's no downtime"], k:1},
   {q:"What happened when he looked at his notes?", a:"\"Sorry, I seem to have lost my train of thought.\"", opts:["He lost his train of thought","He lost his laptop"], k:0},
   {q:"How long is the battery life?", a:"Fifteen years — twice as long as lead-acid.", opts:["Five years","Fifteen years"], k:1},
   {q:"How did he invite questions?", a:"\"I'd like to open the floor for any questions you may have.\"", opts:["No questions, please","I'd like to open the floor"], k:1},
   {q:"Who asked the tough question?", a:"Eng. Samia, the head of the committee.", opts:["Eng. Samia","Hossam's boss"], k:0},
   {q:"How much higher is VoltGuard's price?", a:"12% higher than another offer.", opts:["12%","20%"], k:0},
   {q:"Why is it cheaper over fifteen years?", a:"No battery replacement every five years — the total cost is 8% lower.", opts:["No battery replacement","Free coffee"], k:0},
   {q:"How did he check his answer?", a:"\"Did that answer your question?\"", opts:["Is that clear to you, or not?","Did that answer your question?"], k:1},
   {q:"How did he finish?", a:"\"Thank you all for your attention and time today.\"", opts:["Thank you all for your attention","Goodbye"], k:0}
  ],
  pov:"Now be Hossam closing the tender: \"To recap, we discussed… After careful consideration, our team recommends… Based on the data, we recommend that… Sorry, I seem to have lost my train of thought… I'd like to open the floor for any questions you may have… Did that answer your question?… Thank you all for your attention and time today.\""
 }
});
Object.assign(STORY_AR,{
 pr1:[
  "رنا مهندسة مبيعات في «فولت جارد»، شركة في مدينة نصر بتبيع أنظمة ‎UPS‎ وبتعمل لها صيانة.",
  "النهارده بتعرض عقد صيانة على مجلس إدارة مستشفى «نايل كير» في المنصورة.",
  "«صباح الخير يا جماعة. أجندتنا النهارده هتغطي أربع مواضيع أساسية: أنظمة الـ‎UPS‎ عندكم، والمخاطر، والعقد بتاعنا، والسعر.»",
  "عرضت رسم بياني لتلات وحدات ‎UPS‎ في المستشفى، كل واحدة ‎120 kVA‎. «زي ما حضراتكم شايفين من الرسم ده، وقت التشغيل على البطاريات نزل من عشرين دقيقة لتمانية.»",
  "«ننتقل للموضوع التاني: المخاطر. لو كهربا الشبكة قطعت والبطاريات ضعيفة، أوض العمليات ممكن الكهربا تقطع عنها.»",
  "«إحنا بنفتخر إننا بنقدم حلول مفصّلة على مقاس كل عميل. وبالنسبة لمستشفى، ده معناه زيارة كل تلات شهور ومهندس متاح على مدار الساعة.»",
  "دكتور هشام، المدير المالي للمستشفى، سأل عن التكلفة.",
  "«العقد بـ180 ألف جنيه في السنة. ومفيش أي رسوم أو مصاريف مخفية — المراوح والمكثفات داخلين في العقد.»",
  "فجأة رنا وقفت. كانت ناسية حاجة.",
  "«عايزة أعتذر إني ما ذكرتش تفصيلة مهمة. تغيير البطاريات مش داخل في العقد، وبنعمل له عرض سعر لوحده.»",
  "أعضاء المجلس عجبتهم صراحتها. دكتور هشام هز راسه وكتب ملاحظة.",
  "«لو عندكم أي أسئلة تانية، من فضلكم ما تترددوش تسألوني،» قالتها رنا وهي بتبتسم.",
  "بعد أسبوع، المستشفى مضت العقد."
 ],
 pr2:[
  "طارق كبير مهندسين البطاريات في «فولت جارد». النهارده بيدرّب خمستاشر فني في ورشة الشركة في مدينة 6 أكتوبر.",
  "شوية منهم جايين من إسكندرية وأسيوط من بدري الصبح، وكان باين عليهم التعب.",
  "«شكرًا إنكم خدتوا من وقتكم وجيتوا معانا النهارده. أنا عارف إن وقت كل واحد فيكم غالي، عشان كده هنخلص قبل الساعة تلاتة.»",
  "«الهدف من عرض النهارده إني أوريكم إزاي تركبوا بطاريات الليثيوم أيون وتعملوا لها صيانة بأمان.»",
  "«في آخر العرض ده، هيبقى عندكم فهم واضح للـ‎BMS‎ وإزاي بيحمي كل خلية.»",
  "«هقسّم العرض لتلات أجزاء: السلامة، والتركيب، وحل الأعطال.»",
  "«في جزء السلامة، اتفضلوا ارفعوا إيدكم واسألوا براحتكم. أسئلة السلامة ما تستناش.»",
  "يوسف اللي من أسيوط رفع إيده. «ينفع نستخدم إعدادات الشحن القديمة بتاعة بطاريات الرصاص على الـ‎UPS‎؟»",
  "«سؤال حلو — لأ طبعًا! جهد الشحن مختلف. الإعدادات الغلط ممكن تبوّظ الخلايا أو تخلي الـ‎BMS‎ يفصل.»",
  "في الجزء التاني، طارق وصّل كابينة بطاريات حقيقية بـ‎UPS‎ قدرته ‎60 kVA‎ ووراهم شاشة الـ‎BMS‎.",
  "«الجزء ده طويل، فلو ممكن تأجلوا أسئلتكم لحد الآخر، هيبقى عندنا عشرين دقيقة ليها.»",
  "في الآخر، الفنيين كان عندهم أسئلة كتير — ومحدش بقى باين عليه التعب خالص."
 ],
 pr3:[
  "شريف مدير الصيانة في «فولت جارد». كل ربع سنة بيعرض نتايج قسم الصيانة على المديرين.",
  "الصبح ده، أوضة الاجتماعات في مصر الجديدة كانت مليانة، بس ناس كتير كانوا باصين في موبايلاتهم.",
  "«خلونا نبدأ بأول نقطة أساسية: خلصنا 340 زيارة صيانة الربع ده، يعني 15% أكتر من الربع اللي فات.»",
  "«دلوقتي، حابب أتكلم عن زمن الاستجابة بتاعنا. لأعطال الـ‎UPS‎ في القاهرة، بقى أقل من أربع ساعات.»",
  "ساعتها بالظبط، موبايل عمرو رن. داتا سنتر لعميل في القرية الذكية كان فيه إنذار تبريد.",
  "«لو حد محتاج يخرج، اتفضل براحتك،» قالها شريف بهدوء. وعمرو خرج من الأوضة.",
  "الباقيين كانوا لسه بيقروا إيميلات، فشريف غيّر نبرة صوته.",
  "«حابب ألفت انتباهكم للشاشة. العمود الأحمر ده بيوري أكبر مشكلة عندنا: قطع الغيار اللي بتتأخر.»",
  "«فيه كروت ‎VFD‎ أخدت ست أسابيع لحد ما وصلت من أوروبا. وزي ما قلت قبل كده، زمن الاستجابة بتاعنا سريع — بس من غير قطع غيار، التصليح بيبقى بطيء.»",
  "«وبناءً على كده، بنقترح نعمل مخزون محلي لأكتر عشر قطع بتتطلب في مخزنا في العبور.»",
  "دلوقتي الكل كان باصص للشاشة. المدير العام سأل عن تكلفة المخزون.",
  "«حوالي 2 مليون جنيه،» شريف رد. «لو فيه أي حاجة مش واضحة، من فضلكم قولولي.»",
  "محدش لمس موبايله تاني لحد الآخر."
 ],
 pr4:[
  "ليلى مهندسة طاقة شمسية في «فولت جارد». النهارده عندها اجتماع مع أستاذ عادل، المدير المالي لـ«دلتا باك»، مصنع تغليف في مدينة العاشر من رمضان.",
  "أستاذ عادل بيحب الأرقام، مش الأحلام. «قدامك ربع ساعة،» قالها.",
  "«خليني أشرح لحضرتك الرسم البياني ده خطوة بخطوة. الخط الأزرق ده فاتورة الكهربا الشهرية بتاعتكم في آخر تلات سنين.»",
  "«حصلت زيادة كبيرة جدًا هنا. فاتورتكم طلعت من 400 ألف لـ950 ألف جنيه في الشهر.»",
  "«الأرقام دي بترسم صورة واضحة للوضع الحالي: الطاقة بقت تالت أكبر تكلفة عندكم.»",
  "«ومعروف طبعًا إن مصر فيها من أحسن شمس في العالم. وسطح المصنع عندكم 12 ألف متر مربع — وفاضي.»",
  "«الأبحاث أثبتت إن محطة طاقة شمسية مع تخزين بالبطاريات ممكن تقلل فاتورة كهربا المصنع من 30 لـ40 في المية.»",
  "«وعشان أحط الكلام ده في سياقه، خليني أديك مثال. السنة اللي فاتت بنينا محطة شمسية ‎1 MW‎ لمصنع نسيج في مدينة السادات.»",
  "«وبالبطاريات، مكنهم كمان بتفضل شغالة وقت انقطاع الكهربا القصير. وفترة استرداد التكلفة عندهم كانت أقل من خمس سنين.»",
  "أستاذ عادل بص في الرسم تاني. «ومين اللي هيعمل صيانة للإنفرترات والبطاريات؟»",
  "«إحنا. العرض فيه عقد لمدة خمس سنين مع مراقبة عن بُعد.»",
  "«حابة أفتح باب الأسئلة أو التعليقات،» قالتها ليلى وهي بتبص للفريق كله.",
  "أستاذ عادل ابتسم لأول مرة. «سؤال واحد بس: إمتى تقدروا تبدأوا معاينة الموقع؟»"
 ],
 pr5:[
  "حسام مدير المناقصات في «فولت جارد». النهارده العرض النهائي لداتا سنتر جديد لـ«بنك النيل الرقمي» في العاصمة الإدارية الجديدة.",
  "لجنة البنك فيها سبع أعضاء، وتلات شركات بتتنافس على المشروع.",
  "«كتلخيص، اتكلمنا عن تصميم الكهربا، والتبريد، وخطة التركيب لأوض السيرفرات.»",
  "«بعد دراسة متأنية، فريقنا بيرشّح نظامين ‎UPS‎ موديولار قدرة كل واحد ‎500 kVA‎ ببطاريات ليثيوم أيون.»",
  "«بناءً على البيانات، بنرشّح إنكم تختاروا احتياطي ‎N+1‎، عشان لو موديول واحد عطل ما يحصلش أي توقف.»",
  "بعدين بص في ورقه ووقف. «عمر البطاريات… آسف، يظهر إني تُهت مني الفكرة.»",
  "خد نفس، ولقى الشريحة الصح، وكمّل: «عمر البطاريات خمستاشر سنة — ضعف بطاريات الرصاص.»",
  "«حابب أفتح باب الأسئلة لأي حاجة تحبوا تسألوا عنها.»",
  "المهندسة سامية، رئيسة اللجنة، سألت سؤال صعب: «سعركم أعلى بـ12% من عرض تاني. ليه ندفع أكتر؟»",
  "«عشان مش هتحتاجوا تغيروا البطاريات كل خمس سنين. وعلى مدار خمستاشر سنة، التكلفة الإجمالية عندنا أقل بـ8%.»",
  "«كده جاوبت على سؤال حضرتك؟» حسام سأل. «أيوه، بوضوح جدًا،» ردت سامية.",
  "«شكرًا لكم كلكم على اهتمامكم ووقتكم النهارده،» قالها، وقفل اللابتوب.",
  "بعد أسبوعين، «فولت جارد» كسبت المناقصة."
 ]
});
